// Campus city / preferred airport defaults. Airports are editable route assumptions.
export const teamLocations = {
 Texas:['Austin','Texas','AUS'], GT:['Atlanta','Georgia','ATL'], Purdue:['West Lafayette','Indiana','IND'], Northeastern:['Boston','Massachusetts','BOS'], CMU:['Pittsburgh','Pennsylvania','PIT'], UTD:['Richardson','Texas','DFW'], UCF:['Orlando','Florida','MCO'], UConn:['Storrs','Connecticut','BDL'], UF:['Gainesville','Florida','GNV'], UVA:['Charlottesville','Virginia','CHO'], Rutgers:['New Brunswick','New Jersey','EWR'], TAMU:['College Station','Texas','IAH'], Illini:['Champaign','Illinois','CMI'], UCB:['Berkeley','California','SFO'], Cornell:['Ithaca','New York','ITH'], UMD:['College Park','Maryland','DCA'], Michigan:['Ann Arbor','Michigan','DTW'], GW:['Washington','District of Columbia','DCA'], UCSD:['San Diego','California','SAN'], VCU:['Richmond','Virginia','RIC'], 'Case Western':['Cleveland','Ohio','CLE'], USF:['Tampa','Florida','TPA'], VT:['Blacksburg','Virginia','ROA'], 'Steel City':['Pittsburgh','Pennsylvania','PIT'], UW:['Seattle','Washington','SEA'], WashU:['St. Louis','Missouri','STL'], Columbia:['New York','New York','LGA'], UCLA:['Los Angeles','California','LAX'], IU:['Bloomington','Indiana','IND'], UNC:['Chapel Hill','North Carolina','RDU'], UCSC:['Santa Cruz','California','SJC'], Northwestern:['Evanston','Illinois','ORD'], SBU:['Stony Brook','New York','JFK'], Philthy:['Philadelphia','Pennsylvania','PHL'], Emory:['Atlanta','Georgia','ATL'], OSU:['Columbus','Ohio','CMH'], BU:['Boston','Massachusetts','BOS'], UH:['Houston','Texas','IAH'], Wisconsin:['Madison','Wisconsin','MSN']
};
export const competitionLocations = {
 MANIA:['Champaign','Illinois','CMI'], BND:['Madison','Wisconsin','MSN'], NASHA:['West Lafayette','Indiana','IND'], RAMPAGE:['Orlando','Florida','MCO'], SCR:['Houston','Texas','IAH'], DTX:['Dallas','Texas','DFW'], ROYALTY:['Bloomington','Indiana','IND'], SANEDO:['San Diego','California','SAN'], ATS:['Atlanta','Georgia','ATL'], RDS:['Storrs','Connecticut','BDL'], RCR:['Richmond','Virginia','RIC'], RODEO:['Austin','Texas','AUS'], ECS:['Charlottesville','Virginia','CHO'], NAACH:['New Brunswick','New Jersey','EWR'], MASTI:['College Park','Maryland','DCA'], BNB:['Boston','Massachusetts','BOS'], GGG:['Berkeley','California','SFO']
};
export const labels = {Wisconsin:"Wisconsin Raas",BU:"BU Fatakada",UVA:'HooRaas · UVA',Texas:'Texas DSD',UConn:'UConn Thunderaas',UTD:'UTD TaRaas',UCF:'UCF KnightRaas',Northeastern:'Northeastern Nakhraas',Rutgers:'Rutgers Raga',UW:'UW Raas · Seattle'};

// Team accents reused from the existing bid-points registry; UW corrected to Seattle purple.
export const teamColors={"Texas": "#bf5700", "GT": "#B3A369", "Northeastern": "#d41b2c", "Purdue": "#CEB888", "UTD": "#e87500", "CMU": "#c41230", "UCF": "#FFC904", "UVA": "#232D4B", "Rutgers": "#CC0033", "Cornell": "#B31B1B", "TAMU": "#500000", "UF": "#0021A5", "UMD": "#E21833", "Philthy": "#006bb6", "Michigan": "#FFCB05", "SBU": "#990000", "Steel City": "#003594", "USF": "#006747", "UNC": "#7BAFD4", "Columbia": "#B9D9EB", "VCU": "#F8B800", "UCLA": "#2D68C4", "UCB": "#003262", "UCSC": "#003c6c", "UCSD": "#182B49", "IU": "#990000", "VT": "#861F41", "WashU": "#A51417", "GW": "#033C5A", "OSU": "#BB0000", "Emory": "#012169", "BU": "#CC0000", "Case Western": "#003A70", "Illini": "#E84A27", "UConn": "#000E2F", "Wisconsin": "#C5050C", "UW": "#4b2e83", "UH": "#C8102E", "Northwestern": "#4E2A84"};
