const roster=[
 ['Ashiyana','Carrollton',0],['Ausdin','1718 JPA',1],['Tej','Main St / IRC',1],['Misthi','1725 JPA',0],['Mann','Main St / IRC',1],['Samai','Main St / IRC',0],['Kshema','Main St / IRC',0],['Radhika','1725 JPA',0],['Malav','1725 JPA',0],['Sruthika','Main St / IRC',0],['Syed','1718 JPA',0],['Shlok','Upper JPA / Stadium',0],['Yashaswi','Courtenay',0],['Simran','Carrollton',0],['Malhar','Carrollton',0],['Anjali','',0,1],['Ariya','Main St / IRC',0],['Shikha','Carrollton',0],['Shuprava','Upper JPA / Stadium',0],['Meera','1725 JPA',1],['Rahil','',0,1],['Shawn','',0],['Omkar','',0],['Sanju','',0],['Isha','',0],['Sarim','',0,1]
].map(([name,address,driver])=>({name,address,driver:Boolean(driver),exempt:false,needsRide:true,seats:driver?5:0}));
const defaults={date:'2026-09-01',location:'AFC',time:'8:15–10:45 PM',note:'',published:true,rules:{Yashaswi:{AFC:'noRide'}},roster};
const API_URL='https://hooraas-rides-api.sunkarayashaswi.workers.dev';
const destinations={AFC:{address:'680 Alderman Road, Charlottesville, VA 22903',map:'38.0374,-78.5104'},NRGC:{address:'510 Massie Road, Charlottesville, VA 22903',map:'38.0567,-78.5054'},SRC:{address:'505 Edgemont Road, Charlottesville, VA 22903',map:'38.0408,-78.5161'}};
const practiceSchedule=[['2026-08-30','AFC','8:15–10:45 PM'],['2026-08-31','AFC','9:15–11:45 PM'],['2026-09-01','AFC','8:15–10:45 PM'],['2026-09-02','AFC','8:15–10:45 PM'],['2026-09-06','AFC','8:15–10:45 PM'],['2026-09-07','AFC','9:15–11:45 PM'],['2026-09-08','AFC','8:15–10:45 PM'],['2026-09-09','SRC','8:15–10:45 PM'],['2026-09-13','AFC','8:15–10:45 PM'],['2026-09-14','NRGC','8:15–11:45 PM'],['2026-09-15','NRGC','8:15–10:45 PM'],['2026-09-16','AFC','8:15–10:45 PM'],['2026-09-20','NRGC','8:15–10:45 PM'],['2026-09-21','NRGC','8:15–10:45 PM'],['2026-09-22','NRGC','8:15–10:45 PM'],['2026-09-23','AFC','8:15–10:45 PM'],['2026-09-27','NRGC','8:15–10:45 PM'],['2026-09-28','NRGC','8:15–10:45 PM'],['2026-09-29','NRGC','8:15–10:45 PM'],['2026-09-30','AFC','8:15–10:45 PM'],['2026-10-06','NRGC','8:15–10:45 PM'],['2026-10-07','AFC','8:15–10:45 PM'],['2026-10-11','NRGC','8:15–10:45 PM'],['2026-10-12','NRGC','8:15–10:45 PM'],['2026-10-13','NRGC','8:15–10:45 PM'],['2026-10-14','AFC','8:15–10:45 PM'],['2026-10-18','NRGC','8:15–10:45 PM'],['2026-10-19','NRGC','8:15–10:45 PM'],['2026-10-20','NRGC','8:15–10:45 PM'],['2026-10-21','AFC','8:15–10:45 PM'],['2026-10-25','NRGC','8:15–10:45 PM'],['2026-10-26','NRGC','8:15–10:45 PM'],['2026-10-27','NRGC','8:15–10:45 PM'],['2026-10-28','AFC','8:15–10:45 PM'],['2026-11-01','NRGC','8:15–10:45 PM'],['2026-11-02','NRGC','8:15–10:45 PM'],['2026-11-03','NRGC','8:15–10:45 PM'],['2026-11-04','AFC','8:15–10:45 PM'],['2026-11-08','NRGC','8:15–10:45 PM'],['2026-11-09','NRGC','8:15–10:45 PM'],['2026-11-10','NRGC','8:15–10:45 PM'],['2026-11-11','NRGC','8:15–10:45 PM'],['2026-11-15','NRGC','8:15–10:45 PM'],['2026-11-16','NRGC','8:15–10:45 PM'],['2026-11-17','NRGC','8:15–10:45 PM']];
let state=JSON.parse(localStorage.getItem('hooraas-rides')||'null')||defaults; let current=localStorage.getItem('hooraas-current')||''; let token=localStorage.getItem('hooraas-token')||'';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
async function api(path, options={}){const res=await fetch(API_URL+path,{...options,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})}});const data=await res.json();if(!res.ok)throw new Error(data.error||'Something went wrong.');return data}
function save(){localStorage.setItem('hooraas-rides',JSON.stringify(state));}
async function syncPlan(){if(!token||!document.body.classList.contains('is-manager'))return;await api('/v1/state',{method:'PUT',body:JSON.stringify(state)});}
async function loadRemote(){try{const remote=await api('/v1/state');state=remote;save();render()}catch{token='';current='';localStorage.removeItem('hooraas-token');localStorage.removeItem('hooraas-current');render()}}
function initials(n){return n.split(' ').map(x=>x[0]).join('').slice(0,2)}
function locationName(){return state.location==='AFC'?'Aquatic & Fitness Center':state.location==='NRGC'?'North Grounds Recreation Center':'Slaughter Recreation Center'}
function planRides(){const excluded=new Set(Object.entries(state.rules||{}).filter(([,r])=>r[state.location]==='noRide').map(([n])=>n));const drivers=state.roster.filter(x=>x.driver&&x.needsRide&&!excluded.has(x.name));const riders=state.roster.filter(x=>x.needsRide&&!x.driver&&!excluded.has(x.name));const grouped=drivers.map(x=>({...x,people:[]}));riders.forEach(r=>{const matches=grouped.filter(d=>d.people.length<5&&d.address===r.address);const choices=(matches.length?matches:grouped.filter(d=>d.people.length<5)).sort((a,b)=>a.people.length-b.people.length||a.name.localeCompare(b.name));choices[0]?.people.push(r)});return grouped}
function simpleTime(time){return time.replace('8:15–10:45 PM','8–11 PM').replace('9:15–11:45 PM','9–12 PM')}
function routeUrl(car){const point=destinations[state.location];const stops=car.people.filter(p=>p.address).map(p=>p.address).join('|');return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(car.address||'Charlottesville VA')}&destination=${encodeURIComponent(point.address)}${stops?`&waypoints=${encodeURIComponent(stops)}`:''}&travelmode=driving`}
function render(){const d=new Date(state.date+'T12:00:00');const canView=state.published||document.body.classList.contains('is-manager');$('#practiceDay').textContent=d.toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'}).toUpperCase();$('#publishLabel').textContent=state.published?'Published · visible to team':'Draft · only managers can see changes';$('#practiceLocation').innerHTML=`${locationName()} <span>· ${state.location}</span>`;$('#practiceTime').textContent=`${state.time} · arrive by 10 min early`; const me=state.roster.find(x=>x.name===current);$('#profileInitial').textContent=me?initials(me.name):'?';$('#statusName').textContent=me?`${me.name}'s ride status`:'Sign in to update';
 const allRides=planRides(), rides=document.body.classList.contains('is-manager')?allRides:allRides.filter(r=>r.name===current||r.people.some(p=>p.name===current)); document.body.classList.toggle('role-driver',Boolean(me?.driver));$('#rideCount').textContent=canView?(document.body.classList.contains('is-manager')?`${allRides.length} cars · ${state.roster.filter(x=>x.needsRide&&!x.driver).length} riders`:'Your ride'):'Waiting for manager';$('#rideList').innerHTML=!canView?'<div class="note"><span>i</span><p>Today’s plan is being finalized. You can still sign in to update your pickup or availability.</p></div>':rides.length?rides.map((r,i)=>`<article class="ride-card"><div class="ride-card-top"><div class="driver-avatar">${initials(r.name)}</div><div><h3>${r.name===current?'You are driving':`${r.name} is driving`}</h3><p>${r.seats-r.people.length} seats open · ${r.address||'pickup TBD'}</p></div><span class="seat-count">${r.name===current?'YOUR CAR':`CAR ${String(i+1).padStart(2,'0')}`}</span></div><div class="stops"><div class="stop"><span class="stop-num">START</span><strong>${r.name}</strong><small>${r.address||'Address TBD'}</small></div>${r.people.map((p,j)=>`<div class="stop"><span class="stop-num">STOP ${j+1}</span><strong>${p.name}</strong><small>${p.address||'Pickup TBD'}</small></div>`).join('')}<div class="stop"><span class="stop-num">DESTINATION</span><strong>${state.location}</strong><small>${locationName()}</small></div></div></article>`).join(''):'<div class="note">Your car has not been assigned yet.</div>';
 const point=destinations[state.location];$('#uvaMap').src=`https://www.openstreetmap.org/export/embed.html?layer=mapnik&marker=${point.map}&bbox=-78.525%2C38.028%2C-78.49%2C38.065`;$('#mapKey').textContent=`${state.location} · ${point.address}`;$('#routeSummary').innerHTML=canView?rides.map((r,i)=>`<div class="route-chip"><b>Car ${i+1} · ${r.name}</b><span>${[r,...r.people].map(x=>x.name).join(' → ')} → ${state.location}</span><a href="${routeUrl(r)}" target="_blank">Open this route ↗</a></div>`).join(''):'<div class="route-chip"><b>Route is not published yet</b><span>The manager will share the car and pickup order when ready.</span></div>';$('#scheduleList').innerHTML=practiceSchedule.map(([date,place,time])=>`<div>${date.slice(5)} · <b>${place}</b> · ${time}</div>`).join('');renderManage();}
function renderManage(){if(!document.body.classList.contains('is-manager'))return;$('#dateInput').value=state.date;$('#locationInput').value=state.location;$('#timeInput').value=state.time;$('#noteInput').value=state.note;$('#rosterEditor').innerHTML=state.roster.map((r,i)=>`<div class="roster-row"><div><b>${r.name}</b><div class="address">${r.address||'No pickup location'}</div></div><label>Ride <input data-i="${i}" data-k="needsRide" type="checkbox" ${r.needsRide?'checked':''} ${r.exempt?'disabled':''}></label><label>Drive <input data-i="${i}" data-k="driver" type="checkbox" ${r.driver?'checked':''}></label><button class="text-button" data-edit="${i}">Edit</button></div>`).join('')}
function openModal(which){$('#modalBackdrop').hidden=false;$('#loginModal').hidden=which!=='login';$('#riderModal').hidden=which!=='rider'}function closeModal(){$('#modalBackdrop').hidden=true}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function showRider(){if(!current){openModal('login');return}const r=state.roster.find(x=>x.name===current);$('#riderTitle').textContent=`${r.name}'s ride`;$('#pickupInput').value=r.address;$('#needRideInput').checked=r.needsRide;$('#driveInput').checked=r.driver;openModal('rider')}
async function optimize(){const riders=state.roster.filter(x=>x.needsRide&&!x.driver);const ordered=[...riders].sort((a,b)=>a.address.localeCompare(b.address));const indices=riders.map(x=>state.roster.indexOf(x));indices.forEach((old,i)=>state.roster.splice(state.roster.indexOf(ordered[i]),1)); state.roster.push(...ordered);save();try{await syncPlan();render();toast('Pickup order optimized by neighborhood.')}catch(error){toast(error.message)}}
$('#profileButton').onclick=()=>current?showRider():openModal('login');$('#updateStatus').onclick=showRider;$$('[data-close]').forEach(x=>x.onclick=closeModal);$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))closeModal()};
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active')});
$('#loginSubmit').onclick=async()=>{let name=$('#loginName').value,code=$('#loginCode').value.trim(),inviteCode=$('#inviteCode').value.trim();if(!code.match(/^\d{4,8}$/))return $('#loginError').textContent='Choose a 4–8 digit passcode.';try{let response;try{response=await api('/v1/login',{method:'POST',body:JSON.stringify({name,passcode:code,inviteCode})})}catch(error){if(name!=='Meera'||!error.message.includes('set up first'))throw error;const setupCode=prompt('Enter the one-time manager setup code:');if(!setupCode)return;response=await api('/v1/bootstrap',{method:'POST',body:JSON.stringify({passcode:code,setupCode})})}token=response.token;current=response.member.name;localStorage.setItem('hooraas-token',token);localStorage.setItem('hooraas-current',current);document.body.classList.toggle('is-manager',response.member.role==='manager');await loadRemote();closeModal();render();toast(`Welcome, ${current}.`)}catch(error){$('#loginError').textContent=error.message}};
$('#saveRider').onclick=async()=>{try{await api('/v1/profile',{method:'PUT',body:JSON.stringify({address:$('#pickupInput').value.trim(),needsRide:$('#needRideInput').checked,canDrive:$('#driveInput').checked})});await loadRemote();closeModal();toast('Your ride status has been updated.')}catch(error){toast(error.message)}};
$('#directionsButton').onclick=()=>window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(destinations[state.location].address)}`,'_blank');$('#optimizeButton').onclick=optimize;
$('#savePlan').onclick=async()=>{state.date=$('#dateInput').value;state.location=$('#locationInput').value;state.time=$('#timeInput').value||'Time TBD';state.note=$('#noteInput').value;save();try{await syncPlan();render();toast('Draft saved. Publish when ready.')}catch(error){toast(error.message)}};$('#publishButton').onclick=async()=>{state.published=!state.published;save();try{await syncPlan();render();toast(state.published?'Plan published to the team.':'Plan moved back to draft.')}catch(error){toast(error.message)}};
$('#rosterEditor').onclick=e=>{let i=e.target.dataset.edit;if(i!==undefined){current=state.roster[i].name;showRider()}};$('#rosterEditor').onchange=e=>{let i=e.target.dataset.i,k=e.target.dataset.k;if(i!==undefined){state.roster[i][k]=e.target.checked;if(k==='driver')state.roster[i].seats=e.target.checked?4:0;save();render()}};
$('#showInvites').onclick=async()=>{try{const data=await api('/v1/invites');$('#inviteList').innerHTML=data.pending.length?data.pending.map(x=>`<b>${x.name}</b>: ${x.code}`).join(' · '):'All roster members have claimed their invite code.'}catch(error){toast(error.message)}};
async function loadRequests(){if(!document.body.classList.contains('is-manager'))return;try{const data=await api('/v1/requests');$('#requestQueue').innerHTML=data.requests.length?data.requests.map(r=>`<div class="request-row"><b>${r.name}</b><span>${r.message}</span><button class="button outline" data-request="${r.id}" data-status="approved">Approve</button><button class="button outline" data-request="${r.id}" data-status="dismissed">Dismiss</button></div>`).join(''):'No open requests.'}catch(error){toast(error.message)}}
$('#sendRequest').onclick=async()=>{try{await api('/v1/requests',{method:'POST',body:JSON.stringify({message:$('#requestText').value})});$('#requestText').value='';toast('Request sent to the managers.')}catch(error){toast(error.message)}};$('#refreshRequests').onclick=loadRequests;$('#requestQueue').onclick=async e=>{if(!e.target.dataset.request)return;try{await api(`/v1/requests/${e.target.dataset.request}`,{method:'PUT',body:JSON.stringify({status:e.target.dataset.status})});loadRequests();toast('Request updated.')}catch(error){toast(error.message)}};
$('#dateInput').onchange=()=>{const practice=practiceSchedule.find(x=>x[0]===$('#dateInput').value);if(practice){$('#locationInput').value=practice[1];$('#timeInput').value=practice[2];toast('Loaded the Fall schedule for this date.')}};
$('#addRider').onclick=()=>{let name=prompt('New roster member’s name:');if(name){state.roster.push({name,address:'',driver:false,exempt:false,needsRide:true,seats:0});save();render()}};
$('#loginName').innerHTML=state.roster.map(r=>`<option>${r.name}</option>`).join(''); render();loadRemote();
