import {dailyKey,newRun,difficulty,score,switchLane,step,PLAYER_Y} from './game-engine.mjs';
let board=[],panel,apiBase,frame,run,running=false,result=null,scope='daily',serverDay=dailyKey(),paused=false;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(body){const chosen=scope;const r=await fetch(apiBase+'/v2/game?mode=traffic&scope='+chosen,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const value=await r.json();if(!r.ok)throw new Error(value.error||'Leaderboard unavailable');serverDay=value.day||dailyKey();if(chosen===scope){board=value.scores;paintScores()}}
function paintScores(){document.querySelectorAll('[data-scores]').forEach(el=>{el.innerHTML=board.length?board.slice(0,Number(el.dataset.scores)).map((s,i)=>`<li><span title="${esc(s.name)}">${i+1}. ${esc(s.name)}</span><strong>${s.score}</strong></li>`).join(''):'<li>Be the first on the board.</li>'});document.querySelectorAll('[data-board-scope]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.boardScope===scope)));const selector=document.getElementById('boardScope');if(selector)selector.value=scope}
async function changeScope(value){scope=value;board=[];paintScores();document.querySelectorAll('[data-scores]').forEach(el=>el.innerHTML='<li>Loading…</li>');try{await request()}catch{document.querySelectorAll('[data-scores]').forEach(el=>el.innerHTML='<li>Leaderboard unavailable. Try again.</li>')}}
export function mountGame(app,api){apiBase=api;const section=document.createElement('section');section.className='game-teaser';section.innerHTML='<div><div class="game-title"><h2>Rush hour</h2><span class="game-note">New games whenever I feel like it :)</span></div><p>Three lanes. Incoming traffic. How far can you go?</p><button type="button">Play & leaderboard</button></div><div class="teaser-board"><div class="board-toolbar"><small>TOP 6</small><div role="group" aria-label="Leaderboard period"><button type="button" data-board-scope="daily" aria-pressed="true">Today</button><button type="button" data-board-scope="all" aria-pressed="false">All-time</button></div></div><ol data-scores="6" aria-label="Top six players"></ol></div>';app.append(section);section.querySelector('button').onclick=openGame;section.querySelectorAll('[data-board-scope]').forEach(b=>b.onclick=()=>changeScope(b.dataset.boardScope));paintScores();request().catch(()=>{section.querySelector('[data-scores]').innerHTML='<li>Leaderboard temporarily unavailable.</li>'})}
function openGame(){
 if(!panel){panel=document.createElement('dialog');panel.id='gamePanel';panel.innerHTML=`<div class="heading"><div><small>THE DAILY DRIVE</small><h2>Rush hour</h2></div><button id="closeGame" aria-label="Close game">×</button></div><div class="game-layout"><section class="game-drive"><p id="gameStatus" role="status"></p><canvas id="road" width="480" height="640" tabindex="0" aria-label="Three-lane road. Left and right arrows steer. Keys 1, 2, 3 choose a lane. Space pauses."></canvas><div class="lane-controls" role="group" aria-label="Choose a lane"><button data-lane="0">← Left</button><button data-lane="1">Center</button><button data-lane="2">Right →</button></div><div class="run-actions"><button id="startGame" class="primary">Start endless run</button><button id="pauseGame" hidden>Pause</button></div><p class="game-help">Tap a lane or use ← →. Collect gold stars. Avoid cars, cones and potholes. Space pauses.</p></section><aside class="game-board"><p id="gameTarget"></p><form id="scoreForm" hidden><label>Leaderboard nickname<input name="name" required maxlength="20" autocomplete="nickname"></label><button>Submit score</button></form><p id="scoreNotice" role="status"></p><label>Leaderboard<select id="boardScope"><option value="daily">Daily challenge</option><option value="all">All-time</option></select></label><ol data-scores="10"></ol><small>New three-lane leaderboard. Same course each day. Level up every 15 seconds. Star chains build up to ×5. Late dodges earn +30. Scores are casual and unverified; nicknames are public.</small></aside></div>`;document.body.append(panel);
 panel.querySelector('#closeGame').onclick=()=>panel.close();panel.addEventListener('close',()=>{running=false;paused=false;cancelAnimationFrame(frame)});panel.querySelector('#startGame').onclick=start;
 panel.querySelector('#pauseGame').onclick=togglePause;
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){paused=true;panel.querySelector('#pauseGame').textContent='Resume';panel.querySelector('#gameStatus').textContent='Paused while you were away.';draw();}});
 panel.querySelector('#boardScope').onchange=ev=>changeScope(ev.target.value);
 panel.querySelector('#scoreForm').onsubmit=async ev=>{ev.preventDefault();if(!result)return;const form=ev.target,button=form.querySelector('button'),submission=result;button.disabled=true;try{const name=form.elements.name.value.trim();await request({name,...submission});localStorage.setItem('rides-game-name',name);panel.querySelector('#scoreNotice').textContent='Saved! Your best score stays on the board.';if(result===submission){form.hidden=true;result=null}}catch(err){panel.querySelector('#scoreNotice').textContent=err.message}finally{button.disabled=false}};
 }
 run=null;result=null;panel.querySelector('#scoreForm').hidden=true;panel.querySelector('#gameTarget').textContent='';panel.querySelector('#scoreNotice').textContent='';panel.showModal();panel.querySelector('#startGame').hidden=false;panel.querySelector('#pauseGame').hidden=true;panel.querySelector('#gameStatus').textContent='Pick your lane. Dodge traffic. Collect stars.';panel.querySelector('#scoreForm [name=name]').value=localStorage.getItem('rides-game-name')||'';paintScores();request().catch(()=>{panel.querySelector('#scoreNotice').textContent='Leaderboard unavailable. You can still play.'});draw();
}
function togglePause(){if(!running)return;paused=!paused;panel.querySelector('#pauseGame').textContent=paused?'Resume':'Pause';panel.querySelector('#gameStatus').textContent=paused?'Paused — resume when ready.':'Back on the road.';draw();}
function steer(lane){if(!running||paused)return;switchLane(run,lane);draw();}
function car(ctx,x,y,color,oncoming=false){
 ctx.fillStyle='#101917';ctx.fillRect(x-30,y-26,8,18);ctx.fillRect(x+22,y-26,8,18);ctx.fillRect(x-30,y+17,8,18);ctx.fillRect(x+22,y+17,8,18);
 ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x-25,y-43,50,86,12);ctx.fill();ctx.fillStyle='#263f49';ctx.fillRect(x-18,y+(oncoming?8:-26),36,18);ctx.fillStyle=oncoming?'#fff3c4':'#ee8173';ctx.fillRect(x-20,y+33,10,5);ctx.fillRect(x+10,y+33,10,5);
 ctx.fillStyle=oncoming?'#ee8173':'#fff3c4';ctx.fillRect(x-20,y-38,10,5);ctx.fillRect(x+10,y-38,10,5);
}
function draw(){
 const ctx=panel.querySelector('canvas').getContext('2d');ctx.fillStyle='#263533';ctx.fillRect(0,0,480,640);ctx.fillStyle='#506a47';ctx.fillRect(0,0,20,640);ctx.fillRect(460,0,20,640);
 ctx.strokeStyle='#e8e2a2';ctx.lineWidth=3;ctx.setLineDash([]);for(const x of [25,455]){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,640);ctx.stroke();}
 ctx.strokeStyle='#72867e';ctx.setLineDash([28,26]);ctx.lineDashOffset=run?-(run.elapsed*180)%54:0;for(const x of [167,313]){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,640);ctx.stroke();}ctx.setLineDash([]);
 const laneX=lane=>94+lane*146;
 for(const row of run?.rows||[]){const x=laneX(row.lane),y=row.y;
  if(row.kind==='star'){if(row.collected)continue;ctx.fillStyle='#ffe18a';ctx.font='38px system-ui';ctx.textAlign='center';ctx.fillText('★',x,y+13);}
  else if(row.kind==='car')car(ctx,x,y,'#ed8f79',true);
  else if(row.kind==='cones'){for(const dx of [-20,20]){ctx.fillStyle='#efac58';ctx.beginPath();ctx.moveTo(x+dx,y-25);ctx.lineTo(x+dx-16,y+18);ctx.lineTo(x+dx+16,y+18);ctx.fill();ctx.fillStyle='#fff3dd';ctx.fillRect(x+dx-9,y,18,6);}}
  else{ctx.fillStyle='#101a18';ctx.strokeStyle='#839188';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(x,y,37,22,0,0,Math.PI*2);ctx.fill();ctx.stroke();}
 }
 car(ctx,laneX(run?.lane??1),PLAYER_Y,run?.dead?'#b77369':'#d6efa0');
 panel.querySelectorAll('[data-lane]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.lane)===(run?.lane??1))));
 if(run?.flash>0){ctx.fillStyle='#fff0b6';ctx.font='bold 22px system-ui';ctx.textAlign='center';ctx.fillText(run.feedback,240,45);}
 if(paused||!run||run.dead){ctx.fillStyle='#12211cbb';ctx.fillRect(35,225,410,125);ctx.fillStyle='#f4f7e9';ctx.textAlign='center';ctx.font='bold 30px system-ui';ctx.fillText(paused?'Take a breather':run?.dead?'One more drive?':'Find your rhythm.',240,276);ctx.font='16px system-ui';ctx.fillText(paused?'Press Resume or Space':run?.dead?run.feedback:'Three lanes. One next move.',240,312);}
}
function start(){
 cancelAnimationFrame(frame);running=true;paused=false;result=null;run=newRun(serverDay);let last=performance.now(),bank=0,lastSecond=-1;
 const canvas=panel.querySelector('canvas'),status=panel.querySelector('#gameStatus'),form=panel.querySelector('#scoreForm');form.hidden=true;panel.querySelector('#scoreNotice').textContent='';panel.querySelector('#startGame').hidden=true;panel.querySelector('#pauseGame').hidden=false;panel.querySelector('#pauseGame').textContent='Pause';
 canvas.onpointerdown=ev=>{ev.preventDefault();const rect=canvas.getBoundingClientRect();steer(Math.max(0,Math.min(2,Math.floor((ev.clientX-rect.left)/rect.width*3))));};
 panel.querySelectorAll('[data-lane]').forEach(button=>button.onclick=()=>steer(Number(button.dataset.lane)));
 panel.onkeydown=ev=>{if(ev.target.matches('input,select,textarea'))return;if(['ArrowLeft','ArrowRight','1','2','3',' '].includes(ev.key)){if(ev.key===' '&&ev.target.tagName==='BUTTON')return;ev.preventDefault();if(ev.key===' '){togglePause();return;}steer(ev.key==='ArrowLeft'?Math.max(0,run.lane-1):ev.key==='ArrowRight'?Math.min(2,run.lane+1):Number(ev.key)-1);}};canvas.focus();
 const tick=now=>{if(!running)return;const dt=Math.min((now-last)/1000,.1);last=now;if(!paused){bank+=dt;while(bank>=1/120&&!run.dead){step(run,1/120);bank-=1/120}draw();const second=Math.floor(run.elapsed);if(second!==lastSecond){lastSecond=second;status.textContent='Level '+difficulty(run.elapsed).level+' · '+score(run)+' pts · ×'+Math.min(5,1+Math.floor(run.combo/3));const target=board.filter(s=>s.score>score(run)).at(-1);panel.querySelector('#gameTarget').textContent=target?(target.score-score(run)+1)+' points to beat '+target.name:'Set the score to beat.'}}
 if(run.dead){running=false;result={score:score(run),day:run.day};status.textContent=run.feedback+' '+result.score+' points · Level '+difficulty(run.elapsed).level+' · '+Math.floor(run.elapsed)+'s';panel.querySelector('#startGame').hidden=false;panel.querySelector('#startGame').textContent='Play again';panel.querySelector('#pauseGame').hidden=true;form.hidden=false;return}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);
}
