import {dailyKey,newRun,difficulty,score,switchLane,step} from './game-engine.mjs';
let board=[],panel,apiBase,frame,run,running=false,result=null,scope='daily',serverDay=dailyKey(),paused=false;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(body){const chosen=scope;const r=await fetch(apiBase+'/v2/game?scope='+chosen,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const value=await r.json();if(!r.ok)throw new Error(value.error||'Leaderboard unavailable');serverDay=value.day||dailyKey();if(chosen===scope){board=value.scores;paintScores()}}
function paintScores(){document.querySelectorAll('[data-scores]').forEach(el=>{el.innerHTML=board.length?board.slice(0,Number(el.dataset.scores)).map((s,i)=>`<li><span>${i+1}. ${esc(s.name)}</span><strong>${s.score}</strong></li>`).join(''):'<li>Be the first on the board.</li>'});document.querySelectorAll('[data-board-title]').forEach(el=>el.textContent=scope==='daily'?'TODAY’S TOP 3':'ALL-TIME TOP 3')}
export function mountGame(app,api){apiBase=api;const section=document.createElement('section');section.className='game-teaser';section.innerHTML='<div><div class="game-title"><h2>☠ Dodge the potholes</h2><span class="game-note">New games whenever I feel like it :)</span></div><p>Endless until you crash. Same daily course for everyone.</p><button type="button">Play & leaderboard</button></div><div><small data-board-title>TODAY’S TOP 3</small><ol data-scores="3"></ol></div>';app.append(section);section.querySelector('button').onclick=openGame;paintScores();request().catch(()=>{section.querySelector('[data-scores]').innerHTML='<li>Leaderboard temporarily unavailable.</li>'})}
function openGame(){
 if(!panel){panel=document.createElement('dialog');panel.id='gamePanel';panel.innerHTML='<div class="heading"><h2>☠ Dodge the potholes</h2><button id="closeGame" aria-label="Close game">×</button></div><p id="gameStatus" role="status"></p><canvas id="road" width="320" height="280" tabindex="0" role="button" aria-label="Game road. Tap to switch lanes, or use left and right arrow keys."></canvas><p id="gameTarget"></p><button id="pauseGame" hidden>Pause</button><button id="startGame" class="primary">Start endless run</button><form id="scoreForm" hidden><label>Leaderboard nickname<input name="name" required maxlength="20" autocomplete="nickname"></label><button>Submit score</button></form><p id="scoreNotice" role="status"></p><label>Leaderboard<select id="boardScope"><option value="daily">Daily challenge</option><option value="all">All-time</option></select></label><ol data-scores="10"></ol><small>Level up every 15 seconds. Skull chains build up to ×5. Late dodges earn +30. Best score per nickname. Casual, unverified scores; nicknames are public.</small>';document.body.append(panel);
 panel.querySelector('#closeGame').onclick=()=>panel.close();panel.addEventListener('close',()=>{running=false;cancelAnimationFrame(frame)});panel.querySelector('#startGame').onclick=start;
 panel.querySelector('#pauseGame').onclick=()=>{paused=!paused;panel.querySelector('#pauseGame').textContent=paused?'Resume':'Pause';panel.querySelector('#gameStatus').textContent=paused?'Paused — resume when ready.':'Back on the road.'};
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){paused=true;panel.querySelector('#pauseGame').textContent='Resume';panel.querySelector('#gameStatus').textContent='Paused while you were away.'}});
 panel.querySelector('#boardScope').onchange=ev=>{scope=ev.target.value;request().catch(e=>panel.querySelector('#scoreNotice').textContent=e.message)};
 panel.querySelector('#scoreForm').onsubmit=async ev=>{ev.preventDefault();if(!result)return;const form=ev.target,button=form.querySelector('button'),submission=result;button.disabled=true;try{const name=form.elements.name.value.trim();await request({name,...submission});localStorage.setItem('rides-game-name',name);panel.querySelector('#scoreNotice').textContent='Saved! Your best score stays on the board.';if(result===submission){form.hidden=true;result=null}}catch(err){panel.querySelector('#scoreNotice').textContent=err.message}finally{button.disabled=false}};
 }
 panel.showModal();panel.querySelector('#startGame').hidden=false;panel.querySelector('#pauseGame').hidden=true;panel.querySelector('#gameStatus').textContent='Tap to switch lanes. Arrow keys choose a lane. Dodge potholes, chain skulls.';panel.querySelector('#scoreForm [name=name]').value=localStorage.getItem('rides-game-name')||'';paintScores();request().catch(()=>{panel.querySelector('#scoreNotice').textContent='Leaderboard unavailable. You can still play.'});draw();
}
function draw(){const ctx=panel.querySelector('canvas').getContext('2d');ctx.fillStyle='#243029';ctx.fillRect(0,0,320,280);ctx.strokeStyle='#a4b7a4';ctx.setLineDash([12,12]);ctx.lineDashOffset=run?-(run.elapsed*70)%24:0;ctx.beginPath();ctx.moveTo(160,0);ctx.lineTo(160,280);ctx.stroke();ctx.setLineDash([]);if(!run)return;
 for(const row of run.rows){const x=row.lane*160+80;ctx.fillStyle='#0b100c';ctx.strokeStyle='#80927e';ctx.beginPath();ctx.ellipse(x,row.y,28,13,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(row.skull&&!row.collected){ctx.fillStyle='#f5f4ce';ctx.font='28px Georgia';ctx.textAlign='center';ctx.fillText('☠',(1-row.lane)*160+80,row.y+9)}}
 ctx.fillStyle=run.dead?'#ca6e63':'#cde8ca';ctx.fillRect(run.lane*160+65,220,30,42);ctx.fillStyle='#243029';ctx.fillRect(run.lane*160+70,225,20,10);
 if(run.flash>0){ctx.fillStyle='#f5f4ce';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText(run.feedback,160,40)}
}
function start(){
 cancelAnimationFrame(frame);running=true;paused=false;result=null;run=newRun(serverDay);let last=performance.now(),bank=0,lastSecond=-1;
 const canvas=panel.querySelector('canvas'),status=panel.querySelector('#gameStatus'),form=panel.querySelector('#scoreForm');form.hidden=true;panel.querySelector('#scoreNotice').textContent='';panel.querySelector('#startGame').hidden=true;panel.querySelector('#pauseGame').hidden=false;panel.querySelector('#pauseGame').textContent='Pause';
 canvas.onpointerdown=ev=>{ev.preventDefault();if(running&&!paused)switchLane(run)};canvas.onkeydown=ev=>{if(['ArrowLeft','ArrowRight',' '].includes(ev.key)){ev.preventDefault();if(running&&!paused)switchLane(run,ev.key==='ArrowLeft'?0:ev.key==='ArrowRight'?1:1-run.lane)}};canvas.focus();
 const tick=now=>{if(!running)return;const dt=Math.min((now-last)/1000,.1);last=now;if(!paused){bank+=dt;while(bank>=1/120&&!run.dead){step(run,1/120);bank-=1/120}draw();const second=Math.floor(run.elapsed);if(second!==lastSecond){lastSecond=second;status.textContent='Level '+difficulty(run.elapsed).level+' · '+score(run)+' pts · ×'+Math.min(5,1+Math.floor(run.combo/3));const target=board.filter(s=>s.score>score(run)).at(-1);panel.querySelector('#gameTarget').textContent=target?(target.score-score(run)+1)+' points to beat '+target.name:'Set the score to beat.'}}
 if(run.dead){running=false;result={score:score(run),day:run.day};status.textContent='Pothole! '+result.score+' points · Level '+difficulty(run.elapsed).level+' · '+Math.floor(run.elapsed)+'s';panel.querySelector('#startGame').hidden=false;panel.querySelector('#startGame').textContent='Play again';panel.querySelector('#pauseGame').hidden=true;form.hidden=false;return}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);
}
