import {plan,participants,destinations,today,pinned} from './model.mjs';
const API=location.hostname==='localhost'||location.hostname==='127.0.0.1'?'http://127.0.0.1:8787':'https://hooraas-rides-api.sunkarayashaswi.workers.dev';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,revision,admin=null,selected=new URLSearchParams(location.search).get('event'),token=localStorage.getItem('rides-admin-token')||localStorage.getItem('hooraas-token')||'',busy=false,map,marker;
function notice(message){$('notice').textContent=message;$('notice').classList.add('show');setTimeout(()=>$('notice').classList.remove('show'),5000)}
async function api(path,body){const response=await fetch(API+'/v2/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not load rides');return result}
function receive(result){data=result.data;revision=result.revision;admin=result.admin;const sorted=[...data.events].sort((a,b)=>a.date.localeCompare(b.date));if(!data.events.some(e=>e.id===selected))selected=(sorted.find(e=>e.date>=today())||sorted.at(-1))?.id;render()}
async function load(){try{receive(await api('state'))}catch(error){if(!data)$('app').innerHTML='<p class="error">Could not load rides. Please refresh to try again.</p>';notice(error.message)}}
async function save(next,verifyId){if(busy)throw new Error('Please wait for the current save.');busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{const response=await fetch(API+'/v2/state',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({data:next,revision,verifyId})});const result=await response.json();if(!response.ok)throw new Error(result.error);receive(result);notice(verifyId?'Verified. Everyone can see the checked plan.':'Saved. Rides updated automatically.');return true}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false)}}
const event=()=>data.events.find(e=>e.id===selected);
const option=(id,label,value)=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(label)}</option>`;
const placeOptions=(value,blank='Choose pickup')=>option('',blank,value)+data.locations.map(l=>option(l.id,l.name,value)).join('');
function destination(e){return data.locations.find(l=>l.id===e.destinationId)||destinations[e.location]}
function routeLink(car,e){const end=destination(e);const point=l=>pinned(l)?l.lat+','+l.lng:l.name+', Charlottesville VA';const stops=car.stops.filter(s=>s.location.id!==car.driver.locationId);const chunks=[];let origin=point(car.driver.point||{name:car.driver.name+' pickup'});for(let i=0;i<stops.length||i===0;i+=3){const part=stops.slice(i,i+3);const final=i+3>=stops.length;const dest=final?(end.address||point(end)):point(part.at(-1).location);const via=final?part:part.slice(0,-1);const q=new URLSearchParams({api:'1',origin,destination:dest,travelmode:'driving'});if(via.length)q.set('waypoints',via.map(s=>point(s.location)).join('|'));chunks.push(`<a target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?${esc(q)}">${chunks.length||!final?'Route part '+(chunks.length+1):'Directions'} ↗</a>`);origin=dest}return chunks.join(' · ')}
function render(){
 $('access').textContent=admin?'Sign out · '+admin:'Admin access';if(!data)return;
 const e=event();if(!e){$('app').innerHTML='<p>No events scheduled.</p>';return}const result=plan(data,e);const end=destination(e);
 const dates=[...data.events].sort((a,b)=>a.date.localeCompare(b.date));
 const heading=new Date(e.date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'});
 $('app').innerHTML=`<div class="toolbar"><select id="eventPicker" aria-label="Choose event">${dates.map(x=>option(x.id,x.date+' · '+x.title+' · '+(data.locations.find(l=>l.id===x.destinationId)?.name||destinations[x.location].name),selected)).join('')}</select><button id="copy">Copy rides</button></div><h1>${esc(heading)}</h1><p>${esc(e.title)} · ${esc(end.name)} · ${esc(e.time)}</p><span class="badge ${e.verified?'verified':''}">${e.verified?'Verified by '+esc(e.verified.by):'Unverified · auto-posted'}</span>${e.note?'<p>'+esc(e.note)+'</p>':''}
 ${result.pending.length?'<div class="warning"><strong>Still needs a ride</strong>'+result.pending.map(x=>'<div>'+esc(x.person.name)+' — '+esc(x.reason)+'</div>').join('')+'</div>':''}
 ${result.cars.map(c=>`<section class="car"><div class="carhead"><h2>${esc(c.driver.name)} drives</h2><small>${c.people.length} / ${c.driver.capacity} passengers</small></div><ol><li><strong>${esc(c.driver.point?.name||'Driver pickup missing')}</strong><span>${esc(c.driver.name)}${c.stops.filter(s=>s.location.id===c.driver.locationId).flatMap(s=>s.people).map(p=>', '+esc(p.name)).join('')}</span></li>${c.stops.filter(s=>s.location.id!==c.driver.locationId).map(s=>`<li><strong>${esc(s.location.name)}</strong><span>${s.people.map(p=>esc(p.name)).join(', ')}</span></li>`).join('')}<li>${esc(end.name)}</li></ol>${c.driver.point?routeLink(c,e):''}</section>`).join('')||'<p>No drivers available for this event.</p>'}
 <p class="muted">${result.excluded.length?'No ride: '+result.excluded.map(p=>esc(p.name)).join(', ')+'. ':''}Changes? Message an admin.</p>
 ${admin?`<section><div class="toolbar"><h2>Admin</h2><button id="verify" class="primary">Verify rides</button></div><p class="muted">Changes save and post immediately. Any edit clears verification.</p>${result.warnings.length?'<details><summary>'+result.warnings.length+' pickup pins need checking</summary>'+result.warnings.map(w=>'<div>'+esc(w)+'</div>').join('')+'</details>':''}<div class="toolbar"><button id="editEvent">Edit event</button><button id="newEvent">New event</button><button id="addPerson">Add person</button></div><h3>Attendance for this event</h3>${participants(data,e).map(p=>`<div class="adminrow"><div><strong>${esc(p.name)}</strong><small>${esc(p.point?.name||'Pickup needed')}</small></div><select aria-label="Ride status for ${esc(p.name)}" data-status="${p.id}">${option('no','No ride',!p.needsRide?'no':p.driver?'drive':'ride')+option('ride','Needs ride',!p.needsRide?'no':p.driver?'drive':'ride')+option('drive','Driving',!p.needsRide?'no':p.driver?'drive':'ride')}</select><select class="assignment" aria-label="Car for ${esc(p.name)}" data-car="${p.id}" ${!p.needsRide||p.driver?'disabled':''}>${option('','Automatic',e.overrides[p.id]?.carId||'')+result.cars.map(c=>option(c.driver.id,c.driver.name,e.overrides[p.id]?.carId)).join('')}</select><button data-person="${p.id}">Edit</button></div>`).join('')}<details><summary>Roster defaults & inactive people</summary>${data.roster.map(p=>`<div class="pinrow"><span>${esc(p.name)}${p.active?'':' (inactive)'}</span><button data-person="${p.id}">Edit</button></div>`).join('')}</details><details><summary>Saved pickup pins</summary><p>Set each pickup once. Pins suggest shorter routes using geographic distance; check driving directions for road access.</p>${data.locations.map(l=>`<div class="pinrow"><span>${esc(l.name)}${pinned(l)?'':' · pin needed'}</span><button data-location="${l.id}">Set pin</button></div>`).join('')}<button id="addLocation">Add location</button></details></section>`:''}`;
 $('eventPicker').onchange=ev=>{selected=ev.target.value;history.replaceState(null,'','?event='+encodeURIComponent(selected));render()};
 $('copy').onclick=async()=>{const text=[heading+' · '+e.title+' · '+end.name+' · '+e.time,e.verified?'Verified by '+e.verified.by:'UNVERIFIED',...result.cars.map(c=>c.driver.name+': '+c.stops.map(s=>s.location.name+' ('+s.people.map(p=>p.name).join(', ')+')').join(' → ')+' → '+end.name),...result.pending.map(x=>'NEEDS ASSIGNMENT: '+x.person.name+' — '+x.reason)].join('\n');try{await navigator.clipboard.writeText(text);notice('Copied rides.')}catch{notice('Copy failed. You can share this page’s URL.')}};
 if(!admin)return;
 $('verify').onclick=()=>save(structuredClone(data),selected).catch(err=>notice(err.message));
 $('addPerson').onclick=()=>editPerson();$('addLocation').onclick=()=>editLocation();$('newEvent').onclick=()=>editEvent();$('editEvent').onclick=()=>editEvent(e);
 document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>editPerson(data.roster.find(p=>p.id===b.dataset.person)));
 document.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>editLocation(data.locations.find(l=>l.id===b.dataset.location)));
 document.querySelectorAll('[data-status],[data-car]').forEach(s=>s.onchange=async()=>{const next=structuredClone(data),ev=next.events.find(x=>x.id===selected),id=s.dataset.status||s.dataset.car;ev.overrides[id]??={};if(s.dataset.status){Object.assign(ev.overrides[id],{needsRide:s.value!=='no',driver:s.value==='drive'});delete ev.overrides[id].carId}else{ev.overrides[id].carId=s.value}try{await save(next)}catch(err){notice(err.message);render()}});
}
function editPerson(p){const f=$('personForm');f.reset();f.elements.id.value=p?.id||'';$('personTitle').textContent=p?'Edit '+p.name:'Add person';for(const k of ['name','capacity'])if(p)f.elements[k].value=p[k];for(const k of ['needsRide','driver','active'])if(p)f.elements[k].checked=p[k];f.querySelectorAll('[name=skip]').forEach(x=>x.checked=p?.skip.includes(x.value)||false);$('personLocations').innerHTML=placeOptions(p?.locationId||'');$('person').showModal()}
function editLocation(l){const f=$('locationForm');f.reset();f.elements.id.value=l?.id||'';f.elements.name.value=l?.name||'';f.elements.lat.value=l?.lat??'';f.elements.lng.value=l?.lng??'';$('location').showModal();if(!globalThis.L){$('pinHelp').textContent='Map could not load. Enter coordinates or refresh to retry.';return}if(!map){map=L.map('pinMap').setView([38.041,-78.505],14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);map.on('click',ev=>setPin(ev.latlng.lat,ev.latlng.lng))}if(marker){map.removeLayer(marker);marker=null}map.invalidateSize();if(pinned(l)){setPin(l.lat,l.lng);map.setView([l.lat,l.lng],17)}else map.setView([38.041,-78.505],14)}
function setPin(lat,lng){const f=$('locationForm');f.elements.lat.value=lat.toFixed(6);f.elements.lng.value=lng.toFixed(6);if(!marker){marker=L.marker([lat,lng],{draggable:true}).addTo(map);marker.on('dragend',()=>{const p=marker.getLatLng();setPin(p.lat,p.lng)})}else marker.setLatLng([lat,lng])}
function editEvent(e){const f=$('eventForm');f.reset();f.elements.id.value=e?.id||'';f.elements.date.value=e?.date||today();for(const k of ['title','time','note','location'])if(e)f.elements[k].value=e[k]||'';$('eventLocations').innerHTML=placeOptions(e?.destinationId||'','Use destination above');$('event').showModal()}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('access').onclick=()=>{if(admin){token='';admin=null;localStorage.removeItem('rides-admin-token');localStorage.removeItem('hooraas-token');load()}else $('login').showModal()};
$('loginForm').onsubmit=async ev=>{ev.preventDefault();try{const response=await api('login',Object.fromEntries(new FormData(ev.target)));token=response.token;localStorage.setItem('rides-admin-token',token);await load();$('login').close();ev.target.reset();$('loginError').textContent=''}catch(err){$('loginError').textContent=err.message}};
$('newLocation').onclick=()=>editLocation();
$('locationForm').onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.target),next=structuredClone(data),id=f.get('id')||crypto.randomUUID(),l={id,name:f.get('name').trim(),lat:Number(f.get('lat')),lng:Number(f.get('lng'))};const i=next.locations.findIndex(x=>x.id===id);if(i>=0)next.locations[i]=l;else next.locations.push(l);try{await save(next);$('location').close();if($('person').open)$('personLocations').innerHTML=placeOptions(id)}catch(err){notice(err.message)}};
$('personForm').onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.target),next=structuredClone(data),id=f.get('id')||crypto.randomUUID();const p={id,name:f.get('name').trim(),locationId:f.get('locationId'),capacity:Number(f.get('capacity')),needsRide:f.has('needsRide'),driver:f.has('driver'),active:f.has('active'),skip:f.getAll('skip')};const i=next.roster.findIndex(x=>x.id===id);if(i>=0&&f.get('pickupScope')==='event'){const current=next.events.find(e=>e.id===selected);current.overrides[id]??={};current.overrides[id].locationId=p.locationId;p.locationId=next.roster[i].locationId;}if(i>=0)next.roster[i]=p;else next.roster.push(p);try{await save(next);$('person').close()}catch(err){notice(err.message)}};
$('eventForm').onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.target),next=structuredClone(data),id=f.get('id')||crypto.randomUUID(),old=next.events.find(e=>e.id===id);const e={...old,id,title:f.get('title').trim(),date:f.get('date'),time:f.get('time'),location:f.get('location'),destinationId:f.get('destinationId'),note:f.get('note'),overrides:old?.overrides||{},verified:null};if(old)next.events[next.events.indexOf(old)]=e;else next.events.push(e);try{await save(next);selected=id;render();$('event').close()}catch(err){notice(err.message)}};
load();setInterval(()=>{if(!admin&&!busy&&!document.querySelector('dialog[open]'))load()},60000);
