import {chromium} from '../../savetheworld/node_modules/playwright/index.mjs';
import {lessons,quiz,diagnostic,exams} from '../content.mjs';
const tasks=[...diagnostic,...lessons.flatMap(l=>l.drills),...quiz,...exams.flatMap(e=>e.tasks)];
if(new Set(tasks.map(q=>q.id)).size!==tasks.length)throw Error('Task IDs must be unique');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.LEARN_URL||'http://127.0.0.1:8098/learn/');
const practice=lessons.filter(l=>l.practice);
const checks=practice.flatMap(l=>l.drills).filter(q=>q.type==='code');
checks.push(...practice.flatMap(l=>l.examples.map((e,i)=>({id:l.id+'-example-'+i,setup:'import pandas as pd\nimport numpy as np',solution:e.code,checks:['assert True']}))));
const failures=await page.evaluate(async tasks=>{const w=new Worker('./worker.mjs',{type:'module'});const bad=[];for(const q of tasks){const r=await new Promise(resolve=>{w.onmessage=({data})=>{if(data.done)resolve(data)};w.postMessage({setup:q.setup,code:q.solution,reference:q.reference,checks:q.checks})});if(r.error||!r.checks?.every(Boolean))bad.push({id:q.id,...r});}w.terminate();return bad;},checks);
if(failures.length)throw Error(JSON.stringify(failures));
console.log(`${checks.length} new coding solutions and worked examples passed`);
await page.getByRole('button',{name:'03 Practice desk'}).click();
await page.locator('[data-lesson="practice-retail"]').first().click();
await page.getByText('Worked example 1 · Currency strings: invalid is not zero',{exact:true}).click();
await page.locator('[data-drill="3"]').click();
await page.locator('#answer-r4').fill(practice.find(l=>l.id==='practice-retail').drills[3].solution);
await page.locator('[data-run="r4"]').click();
await page.waitForFunction(()=>document.querySelector('#output-r4')?.textContent.includes('8/8'),{},{timeout:90000});
await page.getByRole('button',{name:'04 Concept quizzes'}).click();
if(await page.locator('[data-batch]').count()!==4)throw Error('Expected 4 quiz batches');
await page.locator('[data-batch="3"]').click();
if(await page.locator('section[id^="task-"]').count()!==10)throw Error('Missing questions in batch 4');
await page.getByRole('button',{name:'05 Mock exams'}).click();
await page.locator('[data-start="sprint-data"]').click();
if(await page.locator('.exam-question').count()!==3)throw Error('Sprint must show 3 questions');
await page.getByRole('button',{name:'Submit all answers'}).click();
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'03 Practice desk'}).click();
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.screenshot({path:'/private/tmp/learn-expansion-mobile.png',fullPage:true});
if(errors.length)throw Error(errors.join('\n'));
console.log('Practice navigation, worked examples, executable grading, all quiz batches, sprint submission, mobile layout: PASS');
await browser.close();
