import assert from 'node:assert/strict';
const base='http://127.0.0.1:8791/dog';
async function request(path,method='GET',body,token){const res=await fetch(`${base}/${path}`,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json()};}
const name=`api_${Date.now()}`;
assert.equal((await request('day?date=2026-09-15')).status,401);
const pet={name:'Mochi',coat:'cream',collar:'berry',roaming:true};
const account=await request('signup','POST',{username:name,password:'test-password-123',pet});assert.equal(account.status,200);const token=account.data.token;
assert.equal((await request('settings','PUT',{rollover:false},token)).status,200);
assert.equal((await request('login','POST',{username:name,password:'incorrect-password'})).status,401);
assert.equal((await request('signup','POST',{username:name,password:'test-password-123'})).status,409);
const plan={start:600,tasks:[{id:'task-1',name:'Read',minutes:25,group:'Life',done:false,scheduledStart:840}]};
assert.equal((await request('day?date=2026-09-15','PUT',{plan,revision:0},token)).status,200);
assert.equal((await request('day?date=2026-09-15','PUT',{plan,revision:0},token)).status,409);
assert.equal((await request('day?date=2026-02-30','GET',null,token)).status,400);
assert.equal((await request('day?date=2026-09-15','PUT',{plan:{...plan,tasks:[{...plan.tasks[0],minutes:-1}]},revision:1},token)).status,400);
assert.deepEqual((await request('day?date=2026-09-15','GET',null,token)).data.plan,plan);
assert.equal((await request('day?date=2026-09-15','PUT',{plan:{...plan,tasks:[{...plan.tasks[0],scheduledStart:1440}]},revision:1},token)).status,400);
assert.equal((await request('day?date=2026-09-16','GET',null,token)).data.plan,null);
const other=await request('signup','POST',{username:`other_${Date.now()}`,password:'test-password-123'});
assert.equal((await request('day?date=2026-09-15','GET',null,other.data.token)).data.plan,null);
const login=await request('login','POST',{username:name.toUpperCase(),password:'test-password-123'});assert.equal(login.status,200);
assert.deepEqual((await request('day?date=2026-09-15','GET',null,login.data.token)).data.plan,plan);
assert.deepEqual((await request('day?date=2026-09-15','GET',null,token)).data.pet,pet);
assert.equal((await request('profile','PUT',{pet:{...pet,coat:'bad'}},token)).status,400);
const changed={...pet,name:'Pip',coat:'cocoa',roaming:false};
assert.equal((await request('profile','PUT',{pet:changed},token)).status,200);
assert.deepEqual((await request('day?date=2026-09-16','GET',null,token)).data.pet,changed);
assert.equal((await request('day?date=2026-09-15','GET',null,other.data.token)).data.pet.name,'Biscuit');
assert.equal((await request('logout','POST',{},token)).status,200);
assert.equal((await request('day?date=2026-09-15','GET',null,token)).status,401);
console.log('PASS: signup, login, account isolation, date isolation, persistence, validation, revision conflicts, session revocation. Local disposable D1 only.');
