import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../../savetheworld/package.json',import.meta.url));
const {chromium,expect}=require('@playwright/test');
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8095/dog/');
 await page.getByRole('button',{name:'New here? Create an account'}).click();
 const username=`browser_${Date.now()}`;
 await page.getByLabel('Username',{exact:true}).fill(username);
 await page.getByLabel('Password',{exact:true}).fill('test-password-123');
 await page.locator('#signup-pet-name').fill('Mochi');
 await page.getByRole('radio',{name:'Cream',exact:true}).check();
 await page.getByRole('radio',{name:'Berry',exact:true}).check();
 await page.screenshot({path:'/private/tmp/good-day-signup.png',fullPage:true});
 await page.getByRole('button',{name:'Create account →',exact:true}).click();
 await page.locator('#workspace').waitFor({state:'visible'});await page.locator('#close-account').click();
 await expect(page.locator('#pet-menu-name')).toHaveText('Mochi');
 // Care is locked until tasks are completed; customization stays available.
 await page.locator('#pet-menu').click();
 await expect(page.locator('[data-care="meal"]')).toBeDisabled();
 await expect(page.locator('[data-care="walk"]')).toBeDisabled();
 await expect(page.locator('[data-care="rest"]')).toBeDisabled();
 await page.locator('#pet-customize summary').click();
 await page.locator('#pet-name').fill('Pip');
 await page.locator('#pet-coat').selectOption('cocoa');
 await page.locator('#save-pet').click();
 await expect(page.locator('#pet-menu-name')).toHaveText('Pip');
 await page.getByRole('button',{name:'Pause wandering'}).click();
 await page.getByRole('button',{name:'Let wander'}).waitFor();
 await page.locator('#close-pet').click();
 // Paste a list: one save, duration applied to every line, no grouping required.
 await page.locator('#task-name').fill('Read a chapter\nWrite a note\nWalk outside');
 await page.getByRole('button',{name:'15m',exact:true}).click();
 await page.getByRole('button',{name:'+ Add 3 tasks',exact:true}).click();
 await expect(page.locator('.task-row')).toHaveCount(3);
 await expect(page.locator('.task-meta').first()).toContainText('15 min');
 await page.locator('#task-name').fill('Reply to messages');
 await page.locator('#group-details summary').click();
 await page.locator('#group').fill('Work');
 await page.locator('#duration').fill('45');
 await page.locator('#task-name').press('Enter');
 await expect(page.locator('.task-row')).toHaveCount(4);
 await page.getByRole('button',{name:'Start timer for Read a chapter'}).click();
 await expect(page.locator('#pet-wanderer')).toHaveAttribute('data-action','sleep');
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 await page.getByRole('button',{name:'Reset',exact:true}).click();
 await expect(page.locator('#timer')).toHaveText('15:00');
 await page.getByRole('button',{name:'Task finished'}).click();
 await expect(page.locator('#percent')).toHaveText('25%');
 await expect(page.locator('#care-next')).toBeEnabled();
 await page.locator('#care-next').click();
 await expect(page.locator('#care-needs')).toContainText('✓ Meal');
 await page.reload();
 await expect(page.locator('#percent')).toHaveText('25%');
 await expect(page.locator('#pet-menu-name')).toHaveText('Pip');
 await page.locator('#pet-menu').click();
 await page.getByRole('button',{name:'Let wander'}).waitFor();
 await page.getByRole('button',{name:'Let wander'}).click();
 await page.getByRole('button',{name:'Pause wandering'}).waitFor();
 await page.locator('#close-pet').click();
 await page.getByRole('heading',{name:'Today.',exact:true}).click();
 await page.screenshot({path:'/private/tmp/good-day-desktop.png',fullPage:true});
 // A failed save preserves the full draft and the persisted plan.
 await page.route('**/dog/day?*',route=>route.request().method()==='PUT'?route.abort():route.continue());
 await page.locator('#task-name').fill('Keep this draft');
 await page.getByRole('button',{name:'+ Add task',exact:true}).click();
 await page.getByText('Couldn’t connect. Your changes haven’t been saved. Please try again.').waitFor();
 await expect(page.locator('#task-name')).toHaveValue('Keep this draft');
 await expect(page.locator('.task-row')).toHaveCount(4);
 await page.unroute('**/dog/day?*');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/private/tmp/good-day-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.getByRole('button',{name:'Edit Walk outside'}).click();
 await page.locator('#edit-name').fill('Walk to the park');
 await page.getByRole('button',{name:'Save',exact:true}).click();
 await page.locator('#timeline').getByText('Walk to the park',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Edit Walk to the park'}).click();
 await page.getByRole('button',{name:'Delete task',exact:true}).click();
 await page.locator('#edit-dialog').waitFor({state:'hidden'});
 await expect(page.locator('.task-row')).toHaveCount(3);
 await page.locator('#account').click();await page.locator('#logout').click();await page.locator('#auth').waitFor({state:'visible'});
 await expect(page.locator('#pet-menu-name')).toHaveText('Biscuit');
 await page.locator('#username').fill(username);await page.locator('#password').fill('test-password-123');
 await page.getByRole('button',{name:'Log in →',exact:true}).click();
 await expect(page.locator('#pet-menu-name')).toHaveText('Pip');
 await expect(page.locator('#percent')).toHaveText('33%');
 // Reduced-motion is honored even when the saved roaming preference is on.
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.getByRole('heading',{name:'Today.',exact:true}).click();
 assert.equal(await page.locator('#pet-wanderer').evaluate(el=>el.getAnimations().length),0);
 assert.deepEqual(errors,[]);
 console.log('PASS: customized signup, profile persistence, earned care, pause/resume wandering, batch/Enter task entry, durations/groups, focus/rest, rewards, reload/login, edit/delete, failed-save recovery, mobile overflow, reduced motion.');
} finally {await browser.close();}
