import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../../savetheworld/package.json',import.meta.url));
const {chromium,expect}=require('@playwright/test');
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8095/dog/');
 await page.locator('#auth-switch').click();
 await page.locator('#username').fill(`care_${Date.now()}`);await page.locator('#password').fill('test-password-123');await page.locator('#auth-submit').click();
 await expect(page.locator('#workspace')).toBeVisible();await page.locator('#close-account').click();
 await expect(page.locator('#care-next')).toBeDisabled();
 await page.locator('#task-name').fill('Read\nWrite\nStretch');await page.locator('#add-task').click();
 await expect(page.locator('.task-row')).toHaveCount(3);
 await page.getByRole('checkbox',{name:'Complete: Read',exact:true}).click();
 await expect(page.locator('#care-next')).toBeEnabled();await page.locator('#care-next').click();
 await expect(page.locator('#care-needs')).toContainText('✓ Meal');
 await page.getByRole('checkbox',{name:'Complete: Write',exact:true}).click();
 await expect(page.locator('#care-next')).toHaveText('Go sniffing');await page.locator('#care-next').click();
 await expect(page.locator('#pet-toss')).toBeVisible({timeout:15000});
 await page.locator('#pet-toss').focus();await page.keyboard.press('Enter');
 await expect(page.locator('#pet-world-ball')).toBeVisible();
 await page.keyboard.press('Escape');await expect(page.locator('#pet-toss')).toBeHidden();
 await page.getByRole('checkbox',{name:'Complete: Stretch',exact:true}).click();
 await expect(page.locator('#care-next')).toHaveText('Tuck in');await page.locator('#care-next').click();
 await expect(page.locator('#care-summary')).toHaveText('Fed, exercised, and cozy.');
 await expect(page.locator('#pet-wanderer')).toHaveAttribute('data-action','curl',{timeout:15000});
 await page.reload();await expect(page.locator('#care-summary')).toHaveText('Fed, exercised, and cozy.');
 await page.locator('#pet-menu').click();await expect(page.locator('#pet-trick')).toBeEnabled();await expect(page.locator('#pet-memory')).toContainText('after');
 await page.locator('#pet-trick').click();await expect(page.locator('#pet-wanderer')).toHaveAttribute('data-action','paw');
 await page.locator('#timer-toggle').click();await expect(page.locator('#pet-wanderer')).toHaveAttribute('data-action','sleep');
 await page.clock.install();const sleeping=await page.locator('#pet-wanderer').boundingBox();await page.clock.runFor(60000);assert.deepEqual(await page.locator('#pet-wanderer').boundingBox(),sleeping);
 await page.locator('#timer-toggle').click();
 await page.emulateMedia({reducedMotion:'reduce'});const still=await page.locator('#pet-wanderer').boundingBox();await page.clock.runFor(60000);assert.deepEqual(await page.locator('#pet-wanderer').boundingBox(),still);
 assert.equal(await page.locator('#pet-wanderer').evaluate(el=>el.getAnimations({subtree:true}).length),0);
 await page.screenshot({path:'/private/tmp/good-day-care-complete.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.locator('#pet-menu').click();await expect(page.locator('[data-care=meal]')).toBeDisabled();await page.screenshot({path:'/private/tmp/good-day-care-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 console.log('PASS: earned meal/walk/rest, keyboard fetch/Escape, memory and trick persistence, focus immobility, reduced motion, mobile layout.');
}finally{await browser.close();}
