import {useState} from 'react';
import { type Game, type Owner, states, voterGroups, candidateIds, candidateById, primaryBoard, generalBoard, party, totals } from './engine';
import {calculatePrimaryForState} from '../lib/rules/primaryRules';
import {calculateStateWinner} from '../lib/rules/generalElectionRules';
export const label=(id:string)=>id==='blue'?'Blue party':id==='red'?'Red party':candidateById[id as keyof typeof candidateById]?.name??id;
export function Token({owner}:{owner?:Owner}){return <span className={`token ${owner?party(owner):'empty'}`} title={owner?label(owner):'Empty space'}>{owner?(owner.length>4?owner.at(-1):owner==='blue'?'B':'R'):'·'}</span>;}
export function Board({game}:{game:Game}){return <section className="panel"><div className="spread"><h2>Voter group board</h2><span className="muted">5 shared spaces per group</span></div><div className="board-grid">{voterGroups.map(v=>{const slots=game.board[v.id];return <div className="voter-row" key={v.id}><strong>{v.name}</strong><div className="tokens" aria-label={`${v.name}: ${slots.map(label).join(', ')||'empty'}`}>{Array.from({length:5},(_,i)=><Token key={i} owner={slots[i]}/>)}</div></div>;})}</div></section>;}
export function Scoreboard({game}:{game:Game}){const general=game.phase==='general'||game.phase==='complete';const count=totals(game);return <section className="scoreboard" aria-label="Scoreboard">{general?(['blue','red'] as const).map(p=><div key={p} className={`score ${p}`}><span>{p==='blue'?'Blue':'Red'} party</span><strong>{game.phase==='complete'?count[p]:game.nominees[p]?.at(-1)}</strong><small>{game.phase==='complete'?'electoral votes':'nominee'}</small></div>):candidateIds.map(id=><div key={id} className={`score ${party(id)}`}><span>{label(id).replace('Candidate ','')}</span><strong>{game.delegates[id]}</strong><small>delegate points</small></div>)}</section>;}
export function StateExplorer({game}:{game:Game}){
 const [id,setId]=useState(game.schedule[Math.min(game.month,5)]?.[0]||'IA');const [search,setSearch]=useState('');
 const state=states.find(s=>s.id===id)||states[0];const general=game.phase==='general'||game.phase==='complete';
 const recorded=game.primaryResults.find(r=>r.stateId===state.id);const primary=recorded??calculatePrimaryForState(state,primaryBoard(game));
 const result=game.results.find(r=>r.stateId===state.id)??calculateStateWinner(state,generalBoard(game));
 return <section className="panel"><h2>State cards & how we count</h2><p className="muted">Explore the original cards and see exactly where the points come from.</p>
 <label>Find a state<input className="input" placeholder="Search states" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <div className="state-pills">{states.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())).map(s=><button key={s.id} className={`btn ${id===s.id?'btn-primary':''}`} onClick={()=>setId(s.id)}>{s.id}</button>)}</div>
 <div className="spread"><div><h3>{state.name}</h3><p>{state.electoralVotes} electoral votes · {state.primaryType} primary · {state.safeColor==='purple'?'swing':state.safeColor+' lean'} on printed card</p></div><details><summary>Original card</summary><img className="original-state" src={state.image} alt={`Original ${state.name} state card`} loading="lazy"/></details></div>
 {(state.printedTotal!==100||state.printedElectoralVotes!==state.electoralVotes)&&<div className="callout">Source correction: {state.printedTotal!==100?`printed percentages total ${state.printedTotal}%; the game scales these to 100 points. `:''}{state.printedElectoralVotes!==state.electoralVotes?`The printed ${state.printedElectoralVotes} electoral votes are corrected to ${state.electoralVotes}.`:''} Original values remain visible below.</div>}
 <p className="count-caption">{general?`${game.phase==='complete'?'Final':'Live projection'}: Blue ${result.bluePercentage}% · Red ${result.redPercentage}% — ${result.winner==='tie'?'tied':label(result.winner)}`:`${recorded?'Recorded primary result':'If this primary were held now'} · ${state.primaryType==='open'?'3 of 5 spaces needed':'Strict majority within each party needed'}`}</p>
 <div className="table-scroll"><table><thead><tr><th>Voter group</th><th>Printed %</th><th>Game points</th><th>{general?'Party control':'Delegate award'}</th></tr></thead><tbody>{state.voterGroups.map((v,i)=><tr key={v.voterGroupId}><td>{voterGroups.find(g=>g.id===v.voterGroupId)?.name}</td><td>{v.printedPercentage}%</td><td>{v.percentage}</td><td>{general?(()=>{const b=generalBoard(game)[v.voterGroupId];return b.blue===b.red?'Neither (tied / empty)':`${b.blue>b.red?'Blue':'Red'}: ${Math.max(b.blue,b.red)} vs ${Math.min(b.blue,b.red)} tiles`;})():primary.groupResults[i].winners.length?primary.groupResults[i].winners.map(w=>`${label(w)} +${v.percentage}`).join('; '):'No majority → 0 points'}</td></tr>)}</tbody></table></div>
 <p className="muted">Printed percentages represent the game’s simplified groups, not census demographics. A closed primary can award the same group’s points once to each party.</p>
 </section>;
}
