import {useCallback,useEffect,useRef,useState} from 'react';
import {newCode,readSession,saveSession,request,sendAction,sessionKey,savedSessions} from './client';
import type {Session,View,PublicGame} from './service';
import {months,party,candidateIds,candidateById,voterGroups,roundDone,activeCandidate,totals,states,type Action} from './engine';
import {Board,Scoreboard,StateExplorer,label} from './Board';
import {Play,TurnBanner} from './Play';
import Guide,{Adaptations} from './Guide';
import './classroom.css';
const projectCode=new URLSearchParams(location.search).get('monitor')?.toUpperCase();
function download(name:string,text:string,type='application/json'){const link=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type}));link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function ClassroomApp(){
 const [session,setSession]=useState<Session|null>(()=>readSession());const [view,setView]=useState<View|null>(null);const viewRef=useRef<View|null>(null);
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [lastSync,setLastSync]=useState(0);const [now,setNow]=useState(Date.now());
 const [gameId,setGameId]=useState('1');const [tab,setTab]=useState('Play');const [project,setProject]=useState(!!projectCode);const [cycle,setCycle]=useState(true);const [interval,setIntervalSeconds]=useState(8);
 const [guide,setGuide]=useState(false);const [showKey,setShowKey]=useState(false);const [retry,setRetry]=useState<{gameId:string;action:Action;requestId:string;view:View}|null>(null);
 const teacher=session?.actor.role==='teacher'&&!projectCode;
 const accept=useCallback((next:View)=>{if(!viewRef.current||next.code!==viewRef.current.code||next.revision>=viewRef.current.revision){viewRef.current=next;setView(next);}setLastSync(Date.now());},[]);
 const enter=(s:Session)=>{saveSession(s);viewRef.current=null;setView(null);setSession(s);setError('');setGameId(s.actor.gameId||'1');if(!localStorage.getItem(`apgov-guide-${s.actor.role}`))setGuide(true);};
 useEffect(()=>{if(!session&&!projectCode)return;let stopped=false;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const next=await request<View>(projectCode||session!.code,projectCode?'monitor':'state',undefined,projectCode?undefined:session!.token);if(!stopped)accept(next);}catch(e){if(!stopped&&(!viewRef.current||(e as {status?:number}).status===401))setError((e as Error).message);}finally{if(!stopped)timer=setTimeout(poll,1500);}};poll();return()=>{stopped=true;clearTimeout(timer);};},[session,accept]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(!project||!cycle||!view?.games.length)return;const id=setInterval(()=>setGameId(current=>view.games[(Math.max(0,view.games.findIndex(g=>g.id===current))+1)%view.games.length].id),interval*1000);return()=>clearInterval(id);},[project,cycle,interval,view?.games.length]);
 const live=!!lastSync&&now-lastSync<6000;
 const act=async(action:Action,targetId=gameId,pending=retry)=>{
  if(!session||!viewRef.current||busy)return;
  const job=pending??{gameId:targetId,action,requestId:crypto.randomUUID(),view:viewRef.current};setBusy(true);setError('');
  try{accept(await sendAction(session,job.view,job.gameId,job.action,job.requestId));setRetry(null);}catch(e){const err=e as Error&{view?:View;status?:number};if(err.view)accept(err.view);setError(err.message);setRetry(err.status?null:job);}finally{setBusy(false);}
 };
 const leave=()=>{localStorage.removeItem(sessionKey);setSession(null);setView(null);viewRef.current=null;setError('');setLastSync(0);setRetry(null);};
 const game=view?.games.find(g=>g.id===gameId)||view?.games[0];
 useEffect(()=>{if(game&&view?.actor.role==='student')setGameId(game.id);},[game?.id,view?.actor.role]);
 const closeGuide=()=>{setGuide(false);localStorage.setItem(`apgov-guide-${session?.actor.role||'visitor'}`,'1');};
 if(!session&&!projectCode)return <div className="election-app"><Home enter={enter} guide={()=>setGuide(true)}/>{guide&&<Guide onClose={closeGuide}/>}</div>;
 return <div className="election-app"><header className="app-header"><div><span className="eyebrow">AP GOVERNMENT • ELECTION LAB</span><h1>{view?.name||'Connecting to class…'}</h1></div><div className="header-actions"><span className={`connection ${live?'online':'offline'}`} role="status">{live?'● Live':lastSync?'● Reconnecting — play paused':'● Connecting'}</span><button className="btn" onClick={()=>setGuide(true)}>How to play</button>{teacher&&<button className="btn" onClick={()=>setProject(!project)}>{project?'Teacher dashboard':'Smart Board view'}</button>}{!projectCode&&<button className="btn" onClick={leave}>Leave screen</button>}</div></header>
 {error&&<div className="error" role="alert">{error}{retry&&<button className="btn" disabled={busy||!live} onClick={()=>act(retry.action,retry.gameId,retry)}>Retry safely</button>}{!retry&&<button className="btn" onClick={()=>setError('')}>Dismiss</button>}</div>}
 {!live&&lastSync>0&&<div className="callout">Connection interrupted. You can read the last saved board. Actions are disabled until the server reconnects; your cards and seat stay saved.</div>}
 {view&&<><section className="class-strip"><div><span>CLASS CODE</span><strong className="class-code">{view.code}</strong><small>Students: open {location.host}/elections/ → choose your table</small></div>{teacher&&<div className="actions"><button className={`btn ${view.paused?'btn-primary':'pause-button'}`} disabled={busy||!live} onClick={()=>act({type:'pauseAll',value:!view.paused})}>{view.paused?'Resume all tables':'Pause all tables'}</button>{!project&&<button className="btn" disabled={busy||!live||view.paused||view.games.every(g=>g.phase!=='setup')} onClick={()=>act({type:'startAll'})}>Start all ready tables</button>}</div>}</section>
 {view.paused&&<div className="pause-banner" role="status">Class paused by the teacher. Look up at the Smart Board.</div>}
 {project?<><div className="spread project-controls"><h2>Classroom monitor</h2><div className="actions"><button className="btn" onClick={()=>setCycle(!cycle)}>{cycle?'Pause cycling':'Resume cycling'}</button><label>Seconds per table <select value={interval} onChange={e=>setIntervalSeconds(Number(e.target.value))}>{[5,8,10].map(v=><option key={v}>{v}</option>)}</select></label><button className="btn" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>setError('Fullscreen is unavailable in this browser.'));}}>Fullscreen</button></div></div><TableTabs games={view.games} current={game?.id||''} select={setGameId}/>{game&&<Projector game={game}/>}</>:<>
 {teacher&&<><section className="teacher-tools panel"><div className="spread"><div><h2>Teacher desk</h2><p className="muted">1. Share the code · 2. Check six candidate seats per table · 3. Start the games</p></div><div className="actions"><button className="btn" onClick={()=>download(`class-${view.code}.json`,JSON.stringify(view,null,2))}>Download class report</button><button className="btn" onClick={()=>setShowKey(!showKey)}>{showKey?'Hide recovery key':'Teacher recovery key'}</button><a className="btn" href={`?monitor=${view.code}`} target="_blank" rel="noreferrer">Open read-only projector</a></div></div>{showKey&&<div className="private-key"><strong>Private teacher recovery key — save before class; keep off the projector.</strong><p>Use “Restore teacher” on the join screen with class code {view.code} and this key.</p><code>{session!.token}</code><button className="btn" onClick={()=>navigator.clipboard.writeText(session!.token).catch(()=>setError('Select and copy the key manually.'))}>Copy key</button><button className="btn" onClick={()=>download(`teacher-${view.code}-PRIVATE.txt`,`Class: ${view.code}\nTeacher recovery key: ${session!.token}\nRestore at ${location.origin}/elections/\n`,'text/plain')}>Save recovery key</button><button className="btn" onClick={()=>{if(window.confirm('Save the recovery key above first. Lock teacher controls and open the read-only projector? Games will keep running.')){localStorage.removeItem(sessionKey);localStorage.setItem('apgov-recent-sessions',JSON.stringify(savedSessions().filter(s=>s.code!==view.code)));location.assign(`?monitor=${view.code}`);}}}>Lock teacher screen</button></div>}</section><div className="table-overview">{view.games.map(g=><button key={g.id} className={`table-summary ${game?.id===g.id?'selected':''}`} onClick={()=>setGameId(g.id)}><div className="spread"><strong>{g.name}</strong><span>{g.paused?'Paused':g.phase==='setup'?'Joining':months[g.month]}</span></div><b>{g.seats.filter(s=>s.controller).length}/6 candidates</b><small>{g.phase==='setup'?'Waiting to start':roundDone(g)?'Ready for next month':g.seats.find(s=>s.id===activeCandidate(g))?.name||g.phase}</small></button>)}</div></>}
 {game&&<><div className="spread table-title"><h2>{game.name} <span>· {months[game.month]}</span></h2>{teacher&&<div className="actions"><button className="btn" disabled={busy||!live||game.phase==='setup'} onClick={()=>{if(window.confirm('Undo the last game action at this table?'))act({type:'undo'},game.id);}}>Undo last move</button><button className="btn" disabled={busy||!live} onClick={()=>act({type:'pause',value:!game.paused},game.id)}>{game.paused?'Resume this table':'Pause this table'}</button>{game.phase==='setup'&&<><button className="btn" disabled={busy||!live||view.paused||game.paused} onClick={()=>act({type:'assignRemaining'},game.id)}>Assign remaining candidates</button><button className="btn btn-primary" disabled={busy||!live||view.paused||game.paused||game.seats.some(s=>!s.controller)} onClick={()=>act({type:'start'},game.id)}>Start this table</button></>}</div>}</div>
 <TurnBanner game={game}/>
 {(game.phase==='setup'||!game.seats.some(s=>s.controller===view.actor.id)&&view.actor.role==='student')&&<Seats game={game} view={view} busy={busy||!live||!!retry} act={a=>act(a,game.id)}/>}
 <Scoreboard game={game}/><nav className="game-tabs" aria-label="Game sections">{['Play','Voter board','State cards & counting','Calendar','Activity','Results'].map(t=><button className={`btn ${tab===t?'btn-primary':''}`} key={t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {tab==='Play'&&<><Play key={`${game.id}-${game.month}-${game.turn}`} game={game} actor={view.actor} disabled={busy||!live||view.paused||game.paused||!!retry} act={a=>act(a,game.id)}/>{game.phase==='complete'&&<Results game={game}/>}<Board game={game}/></>}
 {tab==='Voter board'&&<Board game={game}/>}{tab==='State cards & counting'&&<StateExplorer key={game.id} game={game}/>}{tab==='Calendar'&&<Calendar game={game}/>}{tab==='Activity'&&<section className="panel"><h2>What happened at {game.name}</h2>{[...game.log].reverse().map((l,i)=><p className="log-row" key={i}><time>{new Date(l.at).toLocaleTimeString()}</time>{l.message}</p>)}</section>}{tab==='Results'&&<Results game={game}/>}
 {teacher&&game.phase!=='setup'&&<details className="panel"><summary>Student connections & seat recovery</summary><p>Release a disconnected candidate so that student can rejoin on another device. Their cards and progress stay with the candidate.</p><Seats game={game} view={view} busy={busy||!live} act={a=>act(a,game.id)}/></details>}
 <Adaptations/></>}
 </>}</>}
 {guide&&<Guide onClose={closeGuide}/>}<footer>Election Lab · Classroom simulation · Progress saves to the class server</footer></div>;
}
function Home({enter,guide}:{enter:(s:Session)=>void;guide:()=>void}){
 const [mode,setMode]=useState('student');const [code,setCode]=useState('');const [className,setClassName]=useState('AP Government');const [count,setCount]=useState(5);const [key,setKey]=useState('');
 const [lobby,setLobby]=useState<{code:string;name:string;games:Array<{id:string;name:string;phase:string;seats:Array<{id:string;taken:boolean}>}>}|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <main className="welcome"><header className="spread"><span className="eyebrow">AP GOVERNMENT • ELECTION LAB</span><button className="btn" onClick={guide}>First time? Take the tour</button></header><div className="welcome-grid"><section><span className="pill">A classroom campaign, from January to November</span><h1>Win the nomination.<br/><em>Build a coalition.</em></h1><p className="lead">Six candidates at each table. Two parties. One path to the presidency. Play from your own device while your teacher follows every campaign.</p><div className="welcome-facts"><div><strong>5+</strong><span>tables, one classroom</span></div><div><strong>51</strong><span>state cards</span></div><div><strong>198</strong><span>strategy & event cards</span></div></div><div className="journey"><span>JAN–JUN<br/><b>Primaries</b></span><span>JUNE<br/><b>Convention</b></span><span>JUL–NOV<br/><b>General election</b></span></div></section>
 <section className="join-panel panel">{savedSessions().length>0&&<details className="recent"><summary>Return to a saved class on this device</summary>{savedSessions().map(s=><button className="btn wide" key={s.code} onClick={()=>enter(s)}>Resume {s.code} · {s.actor.role}{s.actor.gameId?` · Table ${s.actor.gameId}`:''}</button>)}</details>}<nav className="game-tabs"><button className={`btn ${mode==='student'?'btn-primary':''}`} onClick={()=>{setMode('student');setError('');}}>Student</button><button className={`btn ${mode==='teacher'?'btn-primary':''}`} onClick={()=>{setMode('teacher');setError('');}}>Teacher</button><button className={`btn ${mode==='restore'?'btn-primary':''}`} onClick={()=>setMode('restore')}>Restore teacher</button></nav>
 {error&&<p className="error" role="alert">{error}</p>}
 {mode==='teacher'?<form onSubmit={e=>{e.preventDefault();run(async()=>enter(await request<Session>(newCode(),'create',{name:className,count})));}}><h2>Set up your classroom</h2><p>Create one class, then give students its code. Each table has six candidate seats.</p><label>Class name<input className="input" maxLength={80} value={className} onChange={e=>setClassName(e.target.value)}/></label><label>Number of tables<select className="input" value={count} onChange={e=>setCount(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{i+1} table{i?'s':''} · up to {(i+1)*6} students</option>)}</select></label><button className="btn btn-primary wide" disabled={busy}>Create classroom</button><p className="muted">Your private teacher key is created automatically. Save it from the teacher desk to recover on another device.</p></form>:mode==='restore'?<form onSubmit={e=>{e.preventDefault();run(async()=>{const v=await request<View>(code,'state',undefined,key.trim());if(v.actor.role!=='teacher')throw new Error('Use the private teacher key.');enter({code,token:key.trim(),actor:v.actor});});}}><h2>Return to your class</h2><label>Class code<input className="input code-input" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,6))} required minLength={6}/></label><label>Private teacher recovery key<input className="input" type="password" value={key} onChange={e=>setKey(e.target.value)} required/></label><button className="btn btn-primary wide" disabled={busy}>Restore teacher dashboard</button></form>:<><form onSubmit={e=>{e.preventDefault();run(async()=>setLobby(await request(code,'lobby')));}}><h2>Join your campaign</h2><p>Get the six-character class code from the Smart Board.</p><label>Class code<input autoComplete="off" className="input code-input" placeholder="ABC234" value={code} onChange={e=>{setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,6));setLobby(null);}} required minLength={6}/></label><button className="btn btn-primary wide" disabled={busy}>Find my class</button></form>{lobby&&<div className="lobby-tables"><h3>{lobby.name} · Choose your table</h3>{lobby.games.map(g=><button className="btn wide" disabled={busy||g.seats.every(s=>s.taken)} key={g.id} onClick={()=>run(async()=>enter(await request<Session>(code,'join',{gameId:g.id})))}>{g.name} · {g.seats.filter(s=>!s.taken).length} available candidates</button>)}<p className="muted">Candidate already taken after switching devices? Ask your teacher to release your seat.</p></div>}</>}
 </section></div><Adaptations/></main>;
}
function TableTabs({games,current,select}:{games:PublicGame[];current:string;select:(id:string)=>void}){return <nav className="game-tabs">{games.map(g=><button className={`btn ${g.id===current?'btn-primary':''}`} key={g.id} onClick={()=>select(g.id)}>{g.name} · {months[g.month]}</button>)}</nav>;}
function Seats({game:g,view,busy,act}:{game:PublicGame;view:View;busy:boolean;act:(a:Action)=>void}){const [name,setName]=useState('');const teacher=view.actor.role==='teacher';const owned=g.seats.some(s=>s.controller===view.actor.id);return <section className="panel"><h2>{teacher?'Who has joined?':owned?'Your candidate is ready':'Choose your candidate'}</h2>{!teacher&&!owned&&<label>Your first name or nickname<input className="input" maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="First name"/></label>}<div className="seat-grid">{g.seats.map(s=><div className={`seat ${party(s.id)}`} key={s.id}><strong>{label(s.id)}</strong><span>{s.name||'Available'}</span><small>Nominee effects: {candidateById[s.id].effects.map(e=>`${voterGroups.find(v=>v.id===e.voterGroupId)?.name} ${e.delta>0?'+':''}${e.delta}`).join(' · ')}</small><small>{s.controller?Date.now()-(g.lastSeen[s.id]||0)<12000?'Connected':'Waiting for connection':''}{s.id===g.incumbent?' · Incumbent':''}</small>{s.controller===view.actor.id&&<b>Your candidate ✓</b>}{!teacher&&!owned&&!s.controller&&<button className="btn" disabled={busy||!name.trim()} onClick={()=>act({type:'claim',candidate:s.id,name})}>Claim {s.id}</button>}{teacher&&<label>Hand over to<select className="input" value="" disabled={busy} onChange={e=>{if(e.target.value&&window.confirm(`Give ${label(s.id)} to this student?`))act({type:'reassign',candidate:s.id,controller:e.target.value});}}><option value="">Choose a joined student</option>{g.seats.filter((x,i,a)=>x.controller&&x.controller!==s.controller&&a.findIndex(y=>y.controller===x.controller)===i).map(x=><option value={x.controller!} key={x.id}>{x.name}</option>)}</select></label>}{teacher&&s.controller&&<button className="btn" disabled={busy} onClick={()=>{if(window.confirm(`Release ${s.name}’s ${label(s.id)} seat? Their cards and progress stay saved.`))act({type:'release',candidate:s.id});}}>Release seat</button>}</div>)}</div></section>;}
function Calendar({game:g}:{game:PublicGame}){return <section className="panel"><h2>Your game calendar</h2><p>Every month gets a new random turn order. States are shuffled into the primary calendar when the game is created.</p><div className="calendar-grid">{months.map((m,i)=><article className={i===g.month?'selected':''} key={m}><span className="eyebrow">{i<g.month?'COMPLETED':i===g.month?'NOW':'UP NEXT'}</span><h3>{m}</h3><p>{i<6?`${g.schedule[i].length} primaries · one turn each`:i===6?'Choose nominees and platforms':i===10?'October Surprise · two turns each':i===12?'Count all 538 electoral votes':'One turn each for your party'}</p>{i<6&&<small>{g.schedule[i].map(id=>states.find(s=>s.id===id)?.name).join(', ')}</small>}</article>)}</div></section>;}
function Results({game:g}:{game:PublicGame}){const count=totals(g);return <section className="panel"><h2>{g.phase==='complete'?(count.blue===count.red?'269–269: a contingent election':`${count.blue>count.red?'Blue':'Red'} wins the presidency`):'Results & reflection'}</h2>{g.phase!=='complete'?<p>Finish November to reveal the final election. You can inspect primary results in State cards & counting.</p>:<><p className="lead">Blue {count.blue} · Red {count.red} · 270 to win</p><button className="btn" onClick={()=>download(`table-${g.id}-results.csv`,'State,Electoral votes,Blue percent,Red percent,Winner,Coin flip\n'+g.results.map(s=>`${s.stateName},${s.electoralVotes},${s.bluePercentage},${s.redPercentage},${s.winner},${g.coinFlips.includes(s.stateId)?'yes':'no'}`).join('\n'),'text/csv')}>Download results CSV</button><div className="table-scroll"><table><thead><tr><th>State</th><th>Blue %</th><th>Red %</th><th>Winner</th><th>EV</th></tr></thead><tbody>{g.results.map(s=><tr key={s.stateId}><td>{s.stateName}</td><td>{s.bluePercentage}</td><td>{s.redPercentage}</td><td>{s.winner}{g.coinFlips.includes(s.stateId)?' (coin flip)':''}</td><td>{s.electoralVotes}</td></tr>)}</tbody></table></div></>}
 <h3>Discuss at your table</h3><ol><li>How did incumbency help one candidate?</li><li>How did open and closed primaries change the results?</li><li>How did your strategy change after the convention?</li><li>Which groups mattered most to your Electoral College victory? Would a popular vote change your strategy?</li><li>What did this simulation simplify, and how could it be more accurate?</li></ol></section>;}
function Projector({game:g}:{game:PublicGame}){return <main className="projector"><div className="spread"><h2>{g.name}</h2><span>{months[g.month]} · {g.phase==='setup'?`${g.seats.filter(s=>s.controller).length}/6 joined`:g.phase}</span></div><TurnBanner game={g}/><Scoreboard game={g}/><div className="two-col"><section className="panel"><h3>{g.phase==='primary'?'This month’s primaries':'Around the table'}</h3>{g.phase==='primary'?<p className="project-states">{g.schedule[g.month].map(id=>states.find(s=>s.id===id)?.name).join(' · ')}</p>:g.seats.map(s=><p key={s.id}>{label(s.id)} — {s.name||'Waiting to join'}</p>)}</section><section className="panel"><h3>Latest moves</h3>{g.log.slice(-4).reverse().map((l,i)=><p key={i}>{l.message}</p>)}</section></div><details className="panel"><summary>Show voter-group board</summary><Board game={g}/></details></main>;}
