import { useState, useRef, useEffect } from 'react';
const steps=[
 {title:'Six candidates. Two parties. One president.',body:'At your table, three blue candidates and three red candidates compete. January–June: win your party’s nomination. July–November: work with your party to win 270 electoral votes.',note:'Every student keeps playing after the convention—even if someone else becomes the nominee.'},
 {title:'Join your table and claim a candidate',body:'Enter the class code from the Smart Board, select your table, then choose your candidate and enter a first name or nickname. Keep this browser open. Refreshing returns you to the same seat.',note:'Teacher: create five tables, wait for students to join, and start the class. With fewer than six students at a table, assign the remaining candidates to the students who joined.'},
 {title:'Your turn: draw → play → discard → finish',body:'Draw three cards. Play at least one, discard at least one, then finish your turn. You may play a second card; unused cards stay in your hand. The turn banner tells you who acts next.',note:'Only the active candidate can play. Order is shuffled each month. October has two complete rounds.'},
 {title:'Five spaces shared by everyone',body:'Each voter group has five spaces. A + adds your tiles; a − removes your tiles. Empty spaces fill first. When a group is full, you replace another candidate’s tiles. Review or change the replacement before playing.',note:'Example: Blue A has 2 tiles, Red B has 2, and 1 space is empty. Blue A +2 fills the empty space and replaces 1 Red B tile: Blue A 4, Red B 1.'},
 {title:'Count delegates after each primary month',body:'Open primary: a candidate needs 3 of the 5 spaces. Closed primary: count each party separately; a candidate needs more than half of that party’s occupied spaces. A group worth 12% awards 12 classroom delegate points.',note:'No majority means no delegates for that group. The site counts the month once and shows every group’s calculation. These are teaching points, not real party delegate counts.'},
 {title:'Convention: reset and build a coalition',body:'The leading candidate in each party is nominated. Tied leaders agree on a nominee. Each nominee chooses five platform cards from their party’s played cards and hands (or all available if fewer than five).',note:'The app clears primary tiles, restores the printed blue/red shaded spaces, applies platforms, then nominee effects. All six students take turns for their party.'},
 {title:'Election Day and classroom controls',body:'After November, compare party control of each state’s voter groups. Add their percentages; the higher total wins that state’s electoral votes. The site counts all 51 jurisdictions and records a coin flip for tied states.',note:'Teacher: pause one table or the whole class, project a table every 5–10 seconds, and download results. If disconnected, wait for “Live” before playing. Nothing is silently queued offline.'}
];
export default function Guide({onClose}:{onClose:()=>void}){
 const dialog=useRef<HTMLDivElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a,input,select')??[]);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[]);
 const [step,setStep]=useState(0);const [answer,setAnswer]=useState(false);const s=steps[step];
 return <div ref={dialog} className="guide-backdrop" role="dialog" aria-modal="true" aria-label="First game walkthrough"><section className="guide-box">
  <div className="spread"><span className="eyebrow">FIRST GAME • {step+1} / {steps.length}</span><button className="btn" onClick={onClose}>Close tutorial</button></div>
  <div className="guide-progress">{steps.map((_,i)=><button aria-label={`Tutorial step ${i+1}`} key={i} className={i===step?'selected':''} onClick={()=>setStep(i)}/>)}</div>
  <h2>{s.title}</h2><p className="lead">{s.body}</p><div className="callout">{s.note}</div>
  {step===4&&<div className="practice"><strong>Try counting: a closed primary</strong><p>Blue A has 2 spaces, Blue B has 1, and Red A has 2. The group is worth 12%.</p><button className="btn" onClick={()=>setAnswer(!answer)}>{answer?'Hide explanation':'Show who gets the delegates'}</button>{answer&&<p>Blue A wins 12 points (2 of 3 blue tiles). Red A also wins 12 points (2 of 2 red tiles). In an open primary, nobody has 3 tiles, so nobody wins these points.</p>}</div>}
  <div className="spread"><button className="btn" disabled={!step} onClick={()=>setStep(step-1)}>Back</button><button autoFocus className="btn btn-primary" onClick={()=>step===steps.length-1?onClose():setStep(step+1)}>{step===steps.length-1?'Ready to play':'Next'}</button></div>
 </section></div>;
}
export function Adaptations(){return <details className="adaptations"><summary>Online rules & source corrections</summary><div className="prose-block">
 <p>This classroom game follows the supplied Elections Game Instructions, printed state/strategy cards, and shaded Voter Group Board. The older mechanics brainstorm and primary-type spreadsheet sometimes conflict with the printed cards; the printed open/closed labels are used here.</p>
 <ul><li>Each state has 100 classroom delegate points. Printed percentages that total 102 or 104 are proportionally adjusted to 100 using the largest remainder method. State details show both values.</li>
 <li>Electoral votes total 538. Colorado uses 10, New Hampshire 4, and North Dakota 3, correcting printed typos. <a href="https://www.archives.gov/electoral-college/allocation" target="_blank" rel="noreferrer">National Archives allocation</a>.</li>
 <li>The entire map is counted on Election Day instead of preset safe-state totals and three challenges. Every state is winner-take-all for this game, including Maine and Nebraska. A 269–269 result calls for a class discussion of the House contingency procedure.</li>
 <li>General-election control means more party tiles than the opponent; a tied or empty group contributes to neither party. Open primaries require three candidate tiles. Closed primaries require a strict majority within the party.</li>
 <li>January uses Iowa, New Hampshire and South Carolina. Remaining states are shuffled once into February–June (14, 9, 9, 8, 8). This is a game calendar, not a real election schedule.</li>
 <li>To avoid reaction timers on school Wi-Fi, a played Cover-Up protects against the next scandal targeting you (your party after the convention). It does not block ordinary campaigning or tile replacement. The Mic Drop doubles gains on your next numeric card; Debate Walk-Off skips your next turn. The Last Stand uses four different groups.</li>
 <li>Five spaces are shared by all candidates. When full, the default replacement targets the largest opposing-party stack, then other rivals; you can choose another rival per group. If that rival runs out, the same fallback applies. Platform effects alternate parties, with a randomly selected first party; nominee effects follow.</li>
 <li>At the convention, choose five eligible platforms, or all available if fewer than five. Primary hands carry over. Every student remains active as a member of their nominee’s campaign.</li></ul>
 <h3>Original classroom materials</h3><p>{['Elections Game Instructions.docx','State Cards.pdf','Strategy and Event Cards.pdf','Voter Group Board.pptx','Post-Game Questions.docx'].map(name=><a key={name} className="btn" href={`materials/${encodeURIComponent(name)}`} download>{name}</a>)}</p></div></details>;}
