import {useState} from 'react';
import {activeCandidate, canAct, roundDone, candidateIds, candidateById, party, cardById, voterGroups, previewEffects, applyEffects, displacementOptions, nomineeChoices, type Action, type Owner, type Card} from './engine';
import type {PublicGame} from './service';
import type {Actor} from './engine';
import type {Party,VoterGroupId} from '../types';
import {label,Token} from './Board';
type Props={game:PublicGame;actor:Actor;disabled:boolean;act:(action:Action)=>void};
export function TurnBanner({game}:{game:PublicGame}){const active=activeCandidate(game);return <div className={`turn-banner ${active?party(active):''}`}><div><span className="eyebrow">{game.paused?'TABLE PAUSED':game.phase==='setup'?'GETTING READY':game.phase==='convention'?'JUNE CONVENTION':game.phase==='complete'?'ELECTION DAY':roundDone(game)?'MONTH FINISHED':`TURN ${Math.min(game.turn+1,game.order.length)} OF ${game.order.length}`}</span><h2>{game.phase==='setup'?'Waiting for everyone to join':game.phase==='convention'?'Choose your party’s platform':game.phase==='complete'?'Election results':roundDone(game)?'Ready to count or advance':`${game.seats.find(s=>s.id===active)?.name||label(active)}’s turn`}</h2><p>{active&&!roundDone(game)?label(active):game.phase==='setup'?'Your teacher will start the game.':'Follow the next step below.'}{game.month===10?' · October Surprise: two turns each':''}</p></div></div>;}
export function Play({game:g,actor,disabled,act}:Props){
 const mine=g.seats.filter(s=>s.controller===actor.id);const active=activeCandidate(g);const ownActive=canAct(g,actor)&&actor.role==='student';
 const [selected,setSelected]=useState('');const [target,setTarget]=useState<Owner>(g.phase==='general'?(party(active||'blueA')==='blue'?'red':'blue'):candidateIds.find(id=>id!==active)||'redA');
 const [replace,setReplace]=useState<Partial<Record<VoterGroupId,Owner>>>({});const [choices,setChoices]=useState<string[]>(voterGroups.slice(0,4).map(v=>v.id));
 const hand=ownActive?g.hands[active]??[]:mine.flatMap(s=>g.hands[s.id]);const card=hand.includes(selected)?cardById[selected]:null;
 const self:Owner=g.phase==='general'?party(active||'blueA'):active||'blueA';
 const to=card?.type==='Scandal'?target:self;
 let effects:Card['effects']=[];let preview=g.board;let previewError='';
 if(card){try{effects=previewEffects(g,card,to,choices);if(card.type==='Scandal'&&g.shields.includes(to))effects=[];preview=applyEffects(g.board,to,effects,replace);}catch(e){previewError=(e as Error).message;}}
 if(g.phase==='setup')return null;
 if(g.phase==='convention')return <Convention {...{game:g,actor,disabled,act}}/>;
 if(g.phase==='complete')return null;
 if(roundDone(g))return <section className="panel next-step"><h2>{g.phase==='primary'?'Count this month’s primaries':'This month’s turns are complete'}</h2><p>{g.phase==='primary'?`${g.schedule[g.month].length} states are ready. The app will record each result once, add delegate points and advance.`:g.month===11?'Ready for Election Day? All 51 jurisdictions will be counted.':'Advance to a new, randomly ordered round.'}</p><button className="btn btn-primary" disabled={disabled} onClick={()=>act({type:'advance'})}>{g.phase==='primary'?'Count primaries & continue':g.month===11?'Count Election Day':'Start next month'}</button></section>;
 return <section className="panel next-step"><div className="spread"><h2>{ownActive?'Your turn':'Follow the campaign'}</h2><span>{g.deckCount} cards in deck</span></div>
 {ownActive?<><div className="turn-checklist"><span className={g.drawn?'done':''}>1. Draw 3 {g.drawn?'✓':''}</span><span className={g.played?'done':''}>2. Play ≥1 {g.played?'✓':''}</span><span className={g.discarded?'done':''}>3. Discard ≥1 {g.discarded?'✓':''}</span><span>4. Finish</span></div>
 <div className="actions"><button className="btn btn-primary" disabled={disabled||g.drawn} onClick={()=>act({type:'draw'})}>Draw 3 cards</button><button className="btn btn-primary" disabled={disabled||!g.played||!g.discarded} onClick={()=>act({type:'end'})}>Finish turn</button></div><p className="muted">Play one or two cards, discard at least one, and keep the rest. Your hand is private.</p></>:<p>{actor.role==='teacher'?'Students play on their own devices. Use this screen to monitor their progress.':`Wait for ${g.seats.find(s=>s.id===active)?.name||label(active)} to finish. You can study your cards, board and state counts now.`}</p>}
 {g.shields.length>0&&<p className="callout">Cover-Up protection: {g.shields.map(label).join(', ')}. The next targeted scandal is blocked.</p>}
 {g.double.includes(active)&&<p className="callout">The Mic Drop: positive effects on your next numeric card are doubled.</p>}
 {!!hand.length&&<><h3>Your hand · {hand.length} cards</h3><p className="muted">Select a card to preview its effects, then choose Play or Discard.</p><div className="hand">{hand.map(id=><button key={id} className={`hand-card ${selected===id?'selected':''}`} onClick={()=>{setSelected(id);setReplace({});}}><small>{cardById[id].type}</small><strong>{cardById[id].title}</strong><span>{cardById[id].effects.slice(0,2).map(e=>`${voterGroups.find(v=>v.id===e.voterGroupId)?.name} ${e.delta>0?'+':''}${e.delta}`).join(' · ')||specialText(cardById[id])}</span></button>)}</div></>}
 {card&&<div className="card-detail"><div><span className="eyebrow">{card.type}</span><h3>{card.title}</h3><p>{card.description}</p>{card.special&&<p className="callout">{specialText(card)}</p>}
 {card.type==='Scandal'&&<label>Target<select className="input" value={target} onChange={e=>setTarget(e.target.value as Owner)}>{(g.phase==='general'?(['blue','red'] as Owner[]).filter(p=>p!==self):candidateIds.filter(id=>id!==active)).map(id=><option key={id} value={id}>{label(id)}</option>)}</select></label>}
 {card.special==='choose'&&choices.map((id,i)=><label key={i}>{i===0?'Gain 4 tiles':'Lose 1 tile'}<select className="input" value={id} onChange={e=>setChoices(choices.map((v,j)=>j===i?e.target.value:v))}>{voterGroups.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label>)}
 {card.type==='Scandal'&&g.shields.includes(to)&&<p className="callout">This target has Cover-Up protection. This scandal will use up their shield and change no tiles.</p>}<h4>Preview changes to {label(to)}</h4>{effects.map(e=><div className="effect-row" key={e.voterGroupId}><div><strong>{voterGroups.find(v=>v.id===e.voterGroupId)?.name} {e.delta>0?'+':''}{e.delta}</strong><div className="tokens">{Array.from({length:5},(_,i)=><Token key={i} owner={preview[e.voterGroupId][i]}/>)}</div></div>{e.delta>0&&g.board[e.voterGroupId].length+e.delta>5&&displacementOptions(g.board[e.voterGroupId],to).length>0&&<label>Replace first<select className="input" value={replace[e.voterGroupId]||displacementOptions(g.board[e.voterGroupId],to)[0]} onChange={ev=>setReplace({...replace,[e.voterGroupId]:ev.target.value as Owner})}>{displacementOptions(g.board[e.voterGroupId],to).map(id=><option key={id} value={id}>{label(id)}</option>)}</select></label>}</div>)}
 {previewError&&<p role="alert">{previewError}</p>}
 {ownActive&&<div className="actions"><button className="btn btn-primary" disabled={disabled||!g.drawn||g.played>=2||!!previewError} onClick={()=>act({type:'play',card:card.id,target,replace,choices})}>Play this card</button><button className="btn" disabled={disabled||!g.drawn||(!g.played&&hand.length<=1)} onClick={()=>act({type:'discard',card:card.id})}>Discard this card</button></div>}
 </div><details><summary>View printed card</summary><img src={card.image} alt={card.title+' original card'} loading="lazy"/></details></div>}
 </section>;
}
function specialText(card:Card){return card.special==='cover'?'Protect yourself against the next targeted scandal. After the convention, protects your party.':card.special==='double'?'Double positive gains on your next numeric card.':card.special==='skip'?'You will skip your next turn.':card.special==='choose'?'Choose one group to gain 4 and three different groups to lose 1.':card.special==='all'?'Add 2 tiles in every voter group.':'';}
function Convention({game:g,actor,disabled,act}:Props){const [selection,setSelection]=useState<Record<Party,string[]>>({blue:g.platforms.blue,red:g.platforms.red});return <section className="panel next-step"><h2>The national conventions</h2><p>The leading candidates become nominees. Everyone else becomes a campaign teammate and keeps taking turns.</p><div className="two-col">{(['blue','red'] as Party[]).map(p=>{const eligible=g.platformOptions[p];const required=Math.min(5,eligible.length);const ownsParty=actor.role==='teacher'||g.seats.some(s=>s.controller===actor.id&&party(s.id)===p);const ownsNominee=actor.role==='teacher'||g.seats.find(s=>s.id===g.nominees[p])?.controller===actor.id;return <div className={`party-panel ${p}`} key={p}><h3>{p==='blue'?'Blue':'Red'} party</h3><label>Nominee<select className="input" value={g.nominees[p]||''} disabled={disabled||!ownsParty||g.ready[p]} onChange={e=>act({type:'nominate',party:p,candidate:e.target.value})}><option value="">Tied leaders: agree on a nominee</option>{nomineeChoices(g,p).map(id=><option key={id} value={id}>{label(id)} — {g.delegates[id]} points</option>)}</select></label><p>Choose {required} platform cards · {selection[p].length} selected. {required<5?'Your party has fewer than five; use all available cards.':''}</p><div className="platform-list">{eligible.map(id=><label key={id}><input type="checkbox" checked={selection[p].includes(id)} disabled={disabled||!ownsNominee||g.ready[p]||(!selection[p].includes(id)&&selection[p].length>=required)} onChange={e=>setSelection({...selection,[p]:e.target.checked?[...selection[p],id]:selection[p].filter(c=>c!==id)})}/><span><strong>{cardById[id].title}</strong><small>{cardById[id].effects.map(e=>`${voterGroups.find(v=>v.id===e.voterGroupId)?.name} ${e.delta>0?'+':''}${e.delta}`).join(' · ')}</small></span></label>)}</div><button className="btn btn-primary" disabled={disabled||!g.nominees[p]||!ownsNominee||g.ready[p]||selection[p].length!==required} onClick={()=>act({type:'platform',party:p,cards:selection[p]})}>{g.ready[p]?'Platform confirmed ✓':'Confirm platform'}</button>{!ownsNominee&&<p className="muted">The nominee confirms this party’s choices.</p>}</div>;})}</div><div className="callout">Next: primary tiles are cleared; shaded spaces reset; party platforms and nominee strengths are applied automatically. July–November is a team contest.</div><button className="btn btn-primary" disabled={disabled||!g.ready.blue||!g.ready.red} onClick={()=>act({type:'general'})}>Begin the general election</button></section>;}
