import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../../savetheworld/package.json',import.meta.url));
const {chromium}=require('@playwright/test');
const testUrl=process.env.RIDES_TEST_URL;
if(!testUrl||new URL(testUrl).hostname!=='127.0.0.1'||new URL(testUrl).port!=='8094')throw new Error('Use an isolated test UI on 127.0.0.1:8094 with a separate test API/database. Never run write tests on the user preview at 8093.');
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const [width,height] of [[1440,600],[1280,800],[390,844],[375,667]]) {
  await page.setViewportSize({width,height});await page.goto(testUrl);
  await page.locator('.car').first().waitFor();
  if(width>=1000){const tops=await page.locator('.car').evaluateAll(cards=>cards.map(c=>c.getBoundingClientRect().top));assert.equal(new Set(tops).size,1,'All four cars should share one row');}
  assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false,`Vertical overflow at ${width}×${height}`);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.getByRole('button',{name:'Pickup route for Ausdin'}).click();
  await page.locator('#routePanel[open] ol').waitFor();
  await page.getByRole('button',{name:'Close ride details',exact:true}).click();
  assert.equal(await page.locator('dialog[open]').count(),0);
  await page.screenshot({path:`/private/tmp/rides-compact-${width}.png`,fullPage:true});
 }
 await page.getByRole('button',{name:'Admin access',exact:true}).click();
 await page.locator('#loginForm [name=passcode]').fill('194728');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByRole('button',{name:'Edit rides',exact:true}).click();
 await page.getByRole('button',{name:'Verify rides',exact:true}).waitFor();
 await page.getByRole('button',{name:'Add person',exact:true}).click();
 await page.locator('#person[open]').waitFor();
 await page.getByRole('button',{name:'Close',exact:true}).filter({visible:true}).click();
 await page.getByRole('button',{name:'Close edit rides',exact:true}).click();
 await page.getByRole('button',{name:'Locations',exact:true}).click();
 const first=page.locator('#locationsContent [data-location]').first();
 await first.click();
 const original=await page.locator('#locationForm [name=name]').inputValue();
 await page.locator('#locationForm [name=name]').fill(original+' edited');
 await page.getByRole('button',{name:'Save pickup pin',exact:true}).click();
 await page.getByRole('button',{name:'Edit location '+original+' edited',exact:true}).waitFor();
 await page.getByRole('button',{name:'Edit location '+original+' edited',exact:true}).click();
 await page.locator('#locationForm [name=name]').fill(original);
 await page.getByRole('button',{name:'Save pickup pin',exact:true}).click();
 await page.getByRole('button',{name:'Edit location '+original,exact:true}).waitFor();
 await page.getByRole('button',{name:'Add location',exact:true}).click();
 const locationName='Local location test '+Date.now();
 await page.locator('#locationForm [name=name]').fill(locationName);
 await page.locator('#locationForm [name=lat]').fill('38.035');
 await page.locator('#locationForm [name=lng]').fill('-78.505');
 await page.getByRole('button',{name:'Save pickup pin',exact:true}).click();
 await page.getByRole('button',{name:'Edit location '+locationName,exact:true}).waitFor();
 await page.getByRole('button',{name:'Close locations',exact:true}).click();
 await page.reload();await page.getByRole('button',{name:'Locations',exact:true}).click();
 await page.getByRole('button',{name:'Edit location '+locationName,exact:true}).waitFor();
 await page.getByRole('button',{name:'Close locations',exact:true}).click();
 await page.setViewportSize({width:1280,height:800});
 const capacity=page.getByRole('combobox',{name:'Total car capacity for Ausdin',exact:true});
 const previous=await capacity.inputValue();
 await capacity.selectOption('2');
 await page.getByText('Saved. Rides updated automatically.',{exact:true}).waitFor();
 await page.reload();
 await page.getByRole('combobox',{name:'Total car capacity for Ausdin',exact:true}).waitFor();
 assert.equal(await page.getByRole('combobox',{name:'Total car capacity for Ausdin',exact:true}).inputValue(),'2');
 const ausdin=page.locator('.car').filter({has:page.getByRole('heading',{name:'Ausdin drives',exact:true})});
 assert.match(await ausdin.locator('.carhead small').textContent(),/^[0-2]\/2 seats$/);
 await page.getByRole('combobox',{name:'Total car capacity for Ausdin',exact:true}).selectOption(previous);
 await page.getByText('Saved. Rides updated automatically.',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false);
 await page.getByRole('button',{name:'Change ride for Syed',exact:true}).click();
 await page.locator('#rideForm').waitFor();
 assert.match(await page.locator('#recommendation').textContent(),/Recommended:/);
 await page.locator('#rideForm [name=carId]').selectOption({label:'Tej'});
 await page.getByRole('button',{name:'Save ride',exact:true}).click();
 await page.locator('#routePanel').waitFor({state:'hidden'});
 await page.locator('.car').filter({has:page.getByRole('heading',{name:'Tej drives',exact:true})}).getByRole('button',{name:'Change ride for Syed',exact:true}).waitFor();
 await page.getByRole('button',{name:'Change ride for Syed',exact:true}).click();
 await page.locator('#rideForm [name=carId]').selectOption('');
 await page.getByRole('button',{name:'Save ride',exact:true}).click();
 await page.locator('#routePanel').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Edit rides',exact:true}).click();
 await page.getByRole('button',{name:'Add person',exact:true}).click();
 const pendingName='Pending test '+Date.now();
 await page.locator('#personForm [name=name]').fill(pendingName);
 await page.getByRole('button',{name:'Save person',exact:true}).click();
 await page.locator('#person').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Close edit rides',exact:true}).click();
 await page.getByRole('button',{name:'Choose ride for '+pendingName,exact:true}).click();
 await page.locator('#rideForm [name=locationId]').selectOption({label:'Main St / IRC'});
 assert.match(await page.locator('#recommendation').textContent(),/Recommended:/);
 await page.getByRole('button',{name:'Save ride',exact:true}).click();
 await page.locator('#routePanel').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Change ride for '+pendingName,exact:true}).waitFor();
 await page.getByRole('button',{name:'Change ride for '+pendingName,exact:true}).click();
 await page.getByRole('button',{name:'No ride needed',exact:true}).click();
 await page.locator('#routePanel').waitFor({state:'hidden'});
 assert.deepEqual(errors,[]);
 console.log('PASS: compact layout, routes, admin editor, locations, capacity persistence and automatic seat limits. Local data only.');
} finally {await browser.close()}
