import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newRun,step,switchLane,score,difficulty,dailyKey,PLAYER_Y} from '../game-engine.mjs';
function autopilot(run,seconds){for(let i=0;i<seconds*120;i++){const next=run.rows.find(r=>!r.skull&&r.y>=PLAYER_Y-160&&r.y<PLAYER_Y+70);if(next)switchLane(run,next.safeLane);step(run,1/120);assert.equal(run.dead,false)}}
test('three-lane daily course is deterministic and dodgeable for ten minutes',()=>{const a=newRun('2026-09-15'),b=newRun('2026-09-15');autopilot(a,600);autopilot(b,600);assert.deepEqual(a,b);assert(a.elapsed>599);assert(score(a)>2200);assert.equal(difficulty(a.elapsed).level,40);assert(difficulty(10000).interval>=.95);assert(difficulty(10000).speed<=360)});
test('cars collide, late dodges earn a bonus, and only the star lane earns stars',()=>{const a=newRun('day');a.rows=[{lane:1,y:PLAYER_Y-63,kind:'car'}];step(a,.02);assert(a.dead);const b=newRun('day');b.rows=[{lane:1,y:PLAYER_Y-100,kind:'car'},{lane:2,y:PLAYER_Y-100,kind:'star',skull:true}];switchLane(b,2);for(let i=0;i<120;i++)step(b,1/120);assert(!b.dead);assert.equal(b.skulls,1);assert.equal(b.bonus,55);});
test('lane bounds and slow frames cannot skip collisions',()=>{const r=newRun('day');for(const lane of [-1,3,NaN,1.5])switchLane(r,lane);assert.equal(r.lane,1);r.rows=[{lane:1,y:PLAYER_Y-65,kind:'car'}];step(r,1);assert(r.dead);});
test('different seeds vary obstacles and waves never fill all three lanes',()=>{const r=newRun('a'),other=newRun('b');autopilot(r,90);autopilot(other,90);assert.notEqual(r.seed,other.seed);const kinds=new Set();for(let n=0;n<60;n++){const run=newRun('course'+n);autopilot(run,24);for(const row of run.rows){kinds.add(row.kind);if(!row.skull)assert.notEqual(row.lane,row.safeLane);}}assert.deepEqual([...kinds].sort(),['car','cones','pothole','star']);});
test('day changes on Charlottesville midnight',()=>{assert.equal(dailyKey(new Date('2026-09-16T03:59:00Z')),'2026-09-15')});
