import {test} from 'node:test';
import assert from 'node:assert/strict';
import {migrate,plan,validate,today} from '../model.mjs';
function fixture(){const data=migrate({roster:[{name:'Ausdin',address:'1718',driver:true},{name:'Tej',address:'Main',driver:true},{name:'Syed',address:'1718'},{name:'Anjali',address:'Carrollton'},{name:'Rahil'},{name:'Sarim'},{name:'Yashaswi',address:'Courtenay'}]});data.locations.forEach((l,i)=>Object.assign(l,{lat:38+i*.001,lng:-78.5}));return data}
test('default exclusions, date-local overrides and stable home-first grouping',()=>{const d=fixture(),e=d.events[0],a=d.roster.find(p=>p.name==='Anjali');assert.equal(plan(d,e).excluded.length,4);e.overrides[a.id]={needsRide:true};const p=plan(d,e);assert(p.cars.some(c=>c.people.some(x=>x.id===a.id)));assert.equal(plan(d,d.events[1]).excluded.length,4);assert.equal(p.cars[0].stops[0].location.name,'1718');assert.deepEqual(plan(d,e),p);validate(d)});
test('capacity never overflows; missing locations and seats are explicit',()=>{const d=fixture(),e=d.events[0];d.roster[1].active=false;for(let i=0;i<8;i++)d.roster.push({...d.roster[2],id:'extra'+i,name:'extra'+i});d.roster.push({...d.roster[2],id:'missing',name:'missing',locationId:''});const p=plan(d,e);assert.equal(p.cars[0].people.length,5);assert.equal(p.pending.length,5);assert(p.pending.some(x=>x.reason==='Choose pickup location'))});
test('bad manual assignments remain pending, excluded riders never return',()=>{const d=fixture(),e=d.events[0];e.overrides[d.roster[2].id]={carId:'unavailable'};assert.equal(plan(d,e).pending[0].reason,'Selected car unavailable or full');assert.throws(()=>validate(d))});
test('same-location riders form a single stop and do not return home',()=>{const d=fixture(),e=d.events[0];d.roster.push({...d.roster[2],id:'another',name:'Another'});const c=plan(d,e).cars[0];assert.equal(c.stops.length,1);assert.equal(c.stops[0].people.length,2)});
test('Charlottesville date handles UTC midnight',()=>{assert.equal(today(new Date('2026-09-15T01:00:00Z')),'2026-09-14')});
test('coordinates and capacity validated',()=>{const d=fixture();d.roster[0].capacity=6;assert.throws(()=>validate(d));d.roster[0].capacity=5;d.locations[0].lat=100;assert.throws(()=>validate(d))});
