import {readFile,writeFile,copyFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join,dirname,resolve} from 'node:path';
const root=dirname(fileURLToPath(import.meta.url)),out=join(root,'unpacked');
await mkdir(out,{recursive:true});
for(const name of ['manifest.json','background.mjs','model.mjs','bridge.js','popup.html','popup.css','popup.mjs'])await copyFile(join(root,'src',name),join(out,name));
// Bundle our existing renderer, not remote code. No dependency installation.
const profile=(await readFile(resolve(root,'../dog/pet-profile.mjs'),'utf8')).replaceAll('export ','');
const pet=await readFile(resolve(root,'../dog/pet.mjs'),'utf8');
const renderer=pet.slice(pet.indexOf('export function puppySVG'),pet.indexOf('export function createCompanion')).replace('export ','');
if(!renderer.startsWith('function puppySVG'))throw new Error('Task Pup renderer moved; update the build boundary.');
const css=await readFile(join(root,'src/companion.css'),'utf8'),body=await readFile(join(root,'src/content-body.js'),'utf8');
await writeFile(join(out,'content.js'),`// Generated by node taskpup-extension/build.mjs.\n(() => {\n${profile}\n${renderer}\nconst COMPANION_CSS=${JSON.stringify(css)};\n${body}\n})();\n`);
console.log(`Load unpacked: ${out}`);
