import {test,expect} from '@playwright/test';
test('hosted assets, candidate play, teacher recovery and locked projector',async({browser,baseURL},info)=>{
 const teacherContext=await browser.newContext();const teacher=await teacherContext.newPage();const errors:string[]=[];teacher.on('pageerror',e=>errors.push(e.message));await teacher.goto(baseURL!);await teacher.screenshot({path:info.outputPath('homepage.png'),fullPage:true});
 await teacher.getByRole('button',{name:'Teacher',exact:true}).click();await teacher.getByLabel('Class name').fill('Hosted verification');await teacher.getByRole('button',{name:'Create classroom'}).click();await teacher.getByRole('button',{name:'Close tutorial'}).click();await expect(teacher.getByRole('heading',{name:'Teacher desk'})).toBeVisible();
 const session=await teacher.evaluate(()=>JSON.parse(localStorage.getItem('apgov-classroom-session-v1')!));
 const studentContext=await browser.newContext();const student=await studentContext.newPage();student.on('pageerror',e=>errors.push(e.message));await student.goto(baseURL!);await student.getByLabel('Class code',{exact:true}).fill(session.code);await student.getByRole('button',{name:'Find my class'}).click();await student.getByRole('button',{name:/^Table 1 ·/}).click();await student.getByRole('button',{name:'Close tutorial'}).click();await student.getByLabel('Your first name or nickname').fill('QA student');await student.getByRole('button',{name:'Claim blueA',exact:true}).click();await expect(student.getByText('Your candidate ✓')).toBeVisible();
 await expect(teacher.locator('.table-summary').first()).toContainText('1/6 candidates');await teacher.getByRole('button',{name:'Assign remaining candidates'}).click();await expect(teacher.getByRole('button',{name:'Start this table',exact:true})).toBeEnabled();await teacher.getByRole('button',{name:'Start this table',exact:true}).click();
 await expect(student.getByRole('button',{name:'Draw 3 cards',exact:true})).toBeEnabled({timeout:15000});await student.getByRole('button',{name:'Draw 3 cards',exact:true}).click();await expect(student.getByRole('heading',{name:'Your hand · 3 cards'})).toBeVisible();await student.locator('.hand-card').first().click();await student.getByRole('button',{name:'Play this card',exact:true}).click();await expect(student.locator('.turn-checklist')).toContainText('2. Play ≥1 ✓');await student.locator('.hand-card').first().click();await student.getByRole('button',{name:'Discard this card',exact:true}).click();await student.getByRole('button',{name:'Finish turn',exact:true}).click();
 await teacher.getByRole('button',{name:'Pause all tables',exact:true}).click();await expect(student.getByText('Class paused by the teacher. Look up at the Smart Board.')).toBeVisible({timeout:15000});await teacher.getByRole('button',{name:'Resume all tables',exact:true}).click();
 await student.getByRole('button',{name:'State cards & counting',exact:true}).click();await student.getByText('Original card',{exact:true}).click();const cardImage=student.locator('img.original-state');await expect(cardImage).toBeVisible();expect(await cardImage.evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);await student.screenshot({path:info.outputPath('hosted-counting.png'),fullPage:true});
 const recoveryContext=await browser.newContext();const recovered=await recoveryContext.newPage();await recovered.goto(baseURL!);await recovered.getByRole('button',{name:'Restore teacher',exact:true}).click();await recovered.getByLabel('Class code',{exact:true}).fill(session.code);await recovered.getByLabel('Private teacher recovery key').fill(session.token);await recovered.getByRole('button',{name:'Restore teacher dashboard'}).click();await recovered.getByRole('button',{name:'Close tutorial'}).click();await expect(recovered.getByRole('heading',{name:'Teacher desk'})).toBeVisible();
 await recovered.getByRole('button',{name:'Teacher recovery key',exact:true}).click();recovered.on('dialog',d=>d.accept());await recovered.getByRole('button',{name:'Lock teacher screen',exact:true}).click();await expect(recovered.getByRole('heading',{name:'Classroom monitor'})).toBeVisible();await expect(recovered.getByRole('button',{name:'Pause all tables',exact:true})).toHaveCount(0);expect(await recovered.evaluate(()=>localStorage.getItem('apgov-classroom-session-v1'))).toBeNull();await recovered.screenshot({path:info.outputPath('hosted-projector.png'),fullPage:true});
 expect(errors).toEqual([]);await Promise.all([teacherContext.close(),studentContext.close(),recoveryContext.close()]);
});
