import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../../savetheworld/package.json',import.meta.url));
const {chromium}=require('@playwright/test');
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/fares',route=>route.fulfill({json:{quotes:[],flights:false,provider:null,account:null,refresh:{enabled:false,routes:0,priced:0,due:0,intervalDays:7}}}));
 await page.goto('http://127.0.0.1:8107/');await page.getByRole('heading',{name:'HooRaas · UVA',exact:true}).waitFor();
 assert.equal(await page.getByText('Hosting ECS this weekend',{exact:true}).count(),2);
 await page.screenshot({path:'/private/tmp/raas-desktop.png',fullPage:true});
 await page.locator('#strict-rest').check();assert(await page.getByText('fewer events than requested',{exact:false}).isVisible());
 await page.getByRole('button',{name:'Schedule & inputs',exact:true}).click();await page.getByLabel('ECS date',{exact:true}).fill('2027-02-13');await page.getByLabel('ECS date',{exact:true}).blur();
 await page.getByRole('button',{name:'Team forecast',exact:true}).click();assert.equal(await page.getByText('Hosting ECS this weekend',{exact:true}).count(),4);
 await page.getByRole('button',{name:'GGG',exact:true}).click();await page.getByText('Enter a sourced quote or planning estimate',{exact:true}).click();await page.locator('#manual-fare').fill('321');await page.locator('#fare-source').fill('Browser test estimate');await page.getByRole('button',{name:'Save route price',exact:true}).click();await page.getByText('$321 round trip',{exact:true}).waitFor();
 await page.reload();await page.getByRole('button',{name:'GGG',exact:true}).click();await page.getByText('$321 round trip',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Across the circuit',exact:true}).click();await page.getByRole('heading',{name:'The entire competition season'}).waitFor();assert.equal(await page.locator('[data-calendar-comp]').count(),17);assert(await page.locator('[data-calendar-comp] > .section-head > .chip').allTextContents().then(labels=>labels.every(label=>Number(label.split(' ')[0])<=8)));
 await page.getByRole('button',{name:'Team schedules',exact:true}).click();assert.equal(await page.locator('.schedule-grid tbody tr').count(),38);
 await page.getByRole('button',{name:'Fit scores',exact:true}).click();await page.getByRole('heading',{name:'The circuit at a glance'}).waitFor();assert.equal(await page.locator('.heat tbody tr').count(),38);
 await page.getByRole('button',{name:'UVA at ECS',exact:true}).click();await page.getByText('Blocked',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Team forecast',exact:true}).click();await page.screenshot({path:'/private/tmp/raas-mobile.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 const status=await page.request.get('http://127.0.0.1:8107/api/status');assert.equal(status.status(),200);
 const hidden=await page.request.get('http://127.0.0.1:8107/server.mjs');assert.equal(hidden.status(),404);
 await page.setViewportSize({width:1440,height:1080});
 await page.getByRole('button',{name:'Compare schedules',exact:true}).click();await page.locator('#compare-add').selectOption('BU');await page.locator('#compare-add').selectOption('Wisconsin');assert(await page.locator('#compare-add').isDisabled());
 await page.screenshot({path:'/private/tmp/raas-compare.png',fullPage:true});
 await page.getByRole('button',{name:'Save current schedules as baseline',exact:true}).click();await page.locator('.baseline-team').first().waitFor();assert.equal(await page.locator('.baseline-table tr.changed').count(),0);
 await page.locator('[data-team="target"]').fill('0');await page.locator('[data-team="target"]').blur();assert(await page.locator('.baseline-table tr.changed').count()>0);
 const baselineBefore=await page.evaluate(()=>JSON.parse(localStorage.getItem('raas-atlas-v1')).baseline);
 await page.reload();await page.getByRole('button',{name:'Compare schedules',exact:true}).click();await page.getByRole('button',{name:'Baseline vs current',exact:true}).click();assert(await page.locator('.baseline-table tr.changed').count()>0);
 assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('raas-atlas-v1')).baseline),baselineBefore);
 // Simulate a scenario from the prior build: corrections must migrate without resetting edits.
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('raas-atlas-v1'));delete s.teams.Wisconsin;for(const c of s.competitions)if(['BND','BNB','MANIA'].includes(c.id)){c.hosts=[];delete c.hostRevision;}localStorage.setItem('raas-atlas-v1',JSON.stringify(s));});
 await page.reload();await page.getByRole('heading',{name:'HooRaas · UVA',exact:true}).waitFor();const migrated=await page.evaluate(()=>JSON.parse(localStorage.getItem('raas-atlas-v1')));assert.equal(migrated.teams.UVA.target,0);assert.deepEqual(migrated.competitions.find(c=>c.id==='BNB').hosts,['Northeastern','BU']);assert(migrated.teams.Wisconsin);
 await page.locator('#team').selectOption('Northeastern');assert.equal(await page.getByText('Hosting BNB this weekend',{exact:true}).count(),2);
 await page.locator('#team').selectOption('BU');assert.equal(await page.getByText('Hosting BNB this weekend',{exact:true}).count(),2);
 await page.locator('#team').selectOption('Wisconsin');assert.equal(await page.getByText('Hosting BND this weekend',{exact:true}).count(),2);
 await page.getByRole('button',{name:'Across the circuit',exact:true}).click();await page.getByRole('button',{name:'Competition calendar',exact:true}).click();
 await page.screenshot({path:'/private/tmp/raas-calendar.png',fullPage:true});
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export schedules',exact:true}).click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'raas-2026-2027-schedules.csv');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/private/tmp/raas-calendar-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.getByRole('button',{name:'Compare schedules',exact:true}).click();await page.screenshot({path:'/private/tmp/raas-compare-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 await page.setViewportSize({width:1440,height:1080});await page.getByRole('button',{name:'Team forecast',exact:true}).click();await page.locator('#team').selectOption('UVA');await page.locator('[data-team="target"]').fill('4');await page.locator('[data-team="target"]').blur();
 await page.locator('#show-strength').check();await page.locator('.strength-strip:not(.capacity-status)').waitFor();await page.getByText('Why this combination?',{exact:true}).click();assert(await page.locator('.plan-math').textContent().then(t=>t.includes('schedule score')));
 await page.getByRole('button',{name:'Explore historical strength',exact:true}).click();await page.getByRole('heading',{name:'Strength of schedule',exact:true}).waitFor();await page.getByText('56.25',{exact:true}).waitFor();await page.getByText('2025-2026!Y35',{exact:true}).waitFor();
 await page.locator('#strength-lookback').selectOption('5');await page.getByText('42.50',{exact:true}).waitFor();await page.getByText('2021-2022!W29',{exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:/historical schedule$/}).count(),5);await page.screenshot({path:'/private/tmp/raas-strength-five.png',fullPage:true});await page.reload();assert.equal(await page.locator('#strength-lookback').inputValue(),'5');await page.locator('#strength-lookback').selectOption('2');await page.getByRole('button',{name:'Explore historical strength',exact:true}).click();await page.screenshot({path:'/private/tmp/raas-strength.png',fullPage:true});
 await page.getByRole('button',{name:'Try what-if models',exact:true}).click();assert.equal(await page.locator('.whatif-card').count(),7);const beforePreview=await page.evaluate(()=>localStorage.getItem('raas-atlas-v1'));await page.screenshot({path:'/private/tmp/raas-whatif.png',fullPage:true});assert.equal(await page.evaluate(()=>localStorage.getItem('raas-atlas-v1')),beforePreview);
 await page.getByRole('button',{name:'Apply Last 2 seasons',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('raas-atlas-v1')).settings.lookback),2);await page.locator('.strength-strip:not(.capacity-status)').waitFor();
 await page.getByRole('button',{name:'RCR',exact:true}).click();await page.getByRole('heading',{name:'How this score is calculated',exact:true}).waitFor();assert.equal(await page.locator('.explanation > .table-wrap > table > tbody > tr').count(),6);await page.getByRole('heading',{name:'Trip-cost arithmetic',exact:true}).waitFor();await page.screenshot({path:'/private/tmp/raas-explanation.png',fullPage:true});
 await page.getByRole('button',{name:'Across the circuit',exact:true}).click();assert.equal(await page.locator('.field-strength').count(),17);assert(await page.locator('.team-accent').count()>20);
 await page.getByRole('button',{name:'Flight prices',exact:true}).click();await page.getByRole('heading',{name:'Connect Google Flights prices',exact:true}).waitFor();await page.screenshot({path:'/private/tmp/raas-prices.png',fullPage:true});
 const refused=await page.request.post('http://127.0.0.1:8107/api/connection',{data:{apiKey:'not-a-real-key'}});assert.equal(refused.status(),403);
 const malformed=await page.request.post('http://127.0.0.1:8107/api/connection',{headers:{Origin:'http://127.0.0.1:8107'},data:{apiKey:'bad'}});assert.equal(malformed.status(),400);
 const fakeKey='test_key_only_never_a_real_credential';await page.route('**/api/connection',async route=>{assert.equal(route.request().postDataJSON().apiKey,fakeKey);await route.fulfill({json:{flights:true,provider:'SerpApi',account:{plan:'Free',remaining:249,limit:250}}});});
 await page.route('**/api/refresh',async route=>{const body=route.request().postDataJSON();assert(body.routes.length>0&&body.routes.length<383);assert.equal(body.intervalDays,7);await route.fulfill({json:{flights:true,provider:'SerpApi',account:{plan:'Free',remaining:249,limit:250},refresh:{enabled:true,routes:body.routes.length,priced:0,due:body.routes.length,intervalDays:7,message:'Queue started'}}});});
 await page.locator('#serp-key').fill(fakeKey);await page.getByRole('button',{name:'Connect & fetch prices',exact:true}).click();await page.getByText('249 searches remaining of 250 on the verified Free plan.',{exact:true}).waitFor();assert.equal(await page.locator('#serp-key').inputValue(),'');assert(!await page.evaluate(()=>JSON.stringify(localStorage)).then(s=>s.includes(fakeKey)));
 assert(await page.getByText('Queue started',{exact:true}).isVisible());await page.screenshot({path:'/private/tmp/raas-backend-queue.png',fullPage:true});await page.unroute('**/api/connection');await page.unroute('**/api/refresh');
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Team forecast',exact:true}).click();await page.screenshot({path:'/private/tmp/raas-simple-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'Try what-if models',exact:true}).click();await page.screenshot({path:'/private/tmp/raas-whatif-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 console.log('PASS: prior flows plus strength evidence, explanatory arithmetic, optional strength, seven nonmutating previews, preset application, color accents, free connection UI, credential isolation, server origin/input guards, desktop/mobile.');
}finally{await browser.close();}
