import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {YEARS,breakEvidence,restProfile,restPenalty,fieldStrength,ratings,scoreRows,typicalSpringCount} from '../evidence.mjs';
import {freshPlanner,restorePreferences} from '../planner-state.mjs';
import {allocateCircuit} from '../lineups.mjs';
import {week} from '../calendar.mjs';
const data=JSON.parse(await readFile(new URL('../data.json',import.meta.url))),geo=JSON.parse(await readFile(new URL('../geography.json',import.meta.url)));
const make=()=>freshPlanner(data,geo);
function constraints(state,a){for(const f of a.fields){assert(f.count<=8);if(a.complete)assert(f.count>=6);}for(const [t,m] of Object.entries(a.matrix)){const rows=m.plan.rows,ws=rows.map(r=>week(r.competition.date)),hosts=state.competitions.filter(c=>c.hosts.includes(t)).map(c=>week(c.date));assert(rows.length<=state.teams[t].target);assert.equal(new Set(ws).size,ws.length);for(const r of rows){assert(!r.blocked);assert(!hosts.includes(r.cweek));assert(!state.teams[t].unavailable.includes(r.cweek));assert.notEqual(state.teams[t].preferences[r.competition.id],'avoid');if(state.teams[t].strictRest)assert([...hosts,...ws.filter(w=>w!==r.cweek)].every(w=>Math.abs(w-r.cweek)>=14));}}}
test('five spring seasons provide 414 sourced gaps, mostly zero or one, excluding the fall transition',()=>{const b=breakEvidence(data);assert.equal(b.total,414);assert.deepEqual(b.counts,[192,173,38,11]);assert.deepEqual(b.seasons.map(s=>s.counts),[[32,29,4,0],[43,34,8,4],[35,37,18,3],[44,34,2,1],[38,39,6,3]]);assert.equal(Math.round(100*(192+173)/414),88);assert(b.records.every(r=>r.sourceFrom&&r.sourceTo&&r.gap>=0));assert.equal(b.offSeason,1);});
test('missing dates, single appearances and duplicate weeks do not invent gaps',()=>{const season='2025-2026',events=[['A','2026-01-03',['T']],['B','2026-01-04',['T']],['C','2026-01-17',['T','S']],['F','2025-11-01',['T']],['M',null,['T']]].map(([id,date,teams])=>({season,id,date,teams}));const b=breakEvidence({events},[season]);assert.deepEqual(b.counts,[0,1,0,0]);assert.equal(b.byTeam.S.total,0);assert.equal(b.missingDates,1);assert.equal(b.offSeason,1);assert.equal(b.sameWeek,1);assert.equal(b.records[0].gap,1);});
test('empirical rest has explicit zero/one overrides and a two-observation circuit prior',()=>{const b=breakEvidence(data),p=restProfile(data,'UVA'),s={restWeight:20,restMode:'history'},t={rest:'inherit'};assert.equal(p.rates[0],(p.counts[0]+2*b.rates[0])/(p.total+2));assert.equal(restPenalty(p,[0,7],{...s,restMode:'none'},t),0);assert.equal(restPenalty(p,[0,7],{...s,restMode:'one'},t),20);assert.equal(restPenalty(p,[0,14],{...s,restMode:'one'},t),0);assert.equal(restPenalty(p,[0,7],{...s,restWeight:0},t),0);assert.equal(restPenalty(p,[0,7],s,{rest:'none'}),0);assert(Math.abs(restProfile(data,'unknown').rates.reduce((a,b)=>a+b,0)-1)<1e-10);});
test('default draft fills all fields, is repeatable, and preserves hard constraints under edits',()=>{const s=make(),a=allocateCircuit(data,s);assert.equal(s.settings.historyYears,5);assert(a.complete);constraints(s,a);assert.deepEqual(allocateCircuit(data,s),a);const first=a.matrix.UVA.plan.rows[0];s.teams.UVA.preferences[first.competition.id]='avoid';s.teams.UVA.strictRest=true;s.teams.Texas.unavailable=[week(s.competitions[0].date)];const next=allocateCircuit(data,s);constraints(s,next);assert(!next.matrix.UVA.plan.rows.some(r=>r.competition.id===first.competition.id));for(const t of data.teams)s.teams[t].target=0;const empty=allocateCircuit(data,s);assert(!empty.complete);assert.equal(empty.total,0);assert.equal(empty.missing,17*6);});
test('selected historical year cannot use later team results; new fields remain unknown',()=>{const d={events:[{id:'C',season:YEARS[0],teams:['A','B']},{id:'C',season:YEARS[4],teams:['A','B']}],performance:[{team:'A',season:YEARS[0],points:4,appearances:2},{team:'B',season:YEARS[0],points:0,appearances:1},{team:'A',season:YEARS[4],points:8,appearances:2}]};assert.equal(fieldStrength(d,'C',[YEARS[0]]).score,25);assert.equal(ratings(d,[YEARS[0]]).A.score,50);assert.equal(fieldStrength(d,'C',[YEARS[4]]).score,100);assert.equal(fieldStrength(data,'BND').score,null);assert.equal(fieldStrength(data,'BNB').score,null);assert.notEqual(fieldStrength(data,'RCR').score,fieldStrength(data,'RCR',[YEARS.at(-1)]).score);});
test('source data stays immutable on restore; prices and drive-label cutoff cannot affect allocation scores',()=>{const s=make(),original=scoreRows(data,s,'UVA');const raw=structuredClone(s);raw.competitions[0].date='2030-01-01';raw.teams.UVA.lat=0;raw.teams.UVA.driveLimit=1000;raw.teams.UVA.preferences.ECS='prefer';raw.teams.UVA.target=2;raw.settings.travelWeight=999;const restored=restorePreferences(make(),raw);assert.equal(restored.competitions[0].date,s.competitions[0].date);assert.equal(restored.teams.UVA.lat,s.teams.UVA.lat);assert.equal(restored.settings.travelWeight,25);assert.equal(restored.teams.UVA.target,2);const rows=scoreRows(data,restored,'UVA');assert(rows.find(r=>r.competition.id==='ECS').blocked);assert.deepEqual(rows.map(r=>r.rawScore),original.map(r=>r.rawScore));s.routes={fake:999};s.settings.fareMultiplier=100;s.teams.UVA.budget=0;assert.deepEqual(scoreRows(data,s,'UVA'),original);assert.equal(typicalSpringCount(data,'unknown'),3);});
