import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {readFile,mkdtemp} from 'node:fs/promises';import {resolve,extname} from 'node:path';
import {buildAtlas} from '../scripts/build_public.mjs';
const require=createRequire(new URL('../../savetheworld/package.json',import.meta.url)),{chromium}=require('@playwright/test');
const root=await mkdtemp('/private/tmp/atlas-check-');await buildAtlas(resolve('raas-planner'),resolve(root,'atlas'));
const server=createServer(async(req,res)=>{try{if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);return res.end();}const path=new URL(req.url,'http://localhost').pathname,file=resolve(root,'.'+path+(path.endsWith('/')?'index.html':''));if(!file.startsWith(root+'/'))throw Error();const body=await readFile(file);res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.json':'application/json'})[extname(file)]||'text/plain');res.end(body);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(8110,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],writes=[],fares=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url());if(/fares|serpapi|atlas-api/.test(r.url()))fares.push(r.url());});
 await page.goto('http://127.0.0.1:8110/atlas/');await page.getByRole('heading',{name:'Competition lineups'}).waitFor();assert.equal(await page.locator('[data-card]').count(),17);assert(await page.getByText('All 17 lineups have 6–8 teams',{exact:true}).isVisible());for(const c of await page.locator('.lineup-list').all())assert((await c.locator('li').count())>=6&&(await c.locator('li').count())<=8);
 await page.screenshot({path:'/private/tmp/atlas-v2-desktop.png'});
 await page.locator('[data-week]').nth(1).click();assert.equal(await page.locator('[data-card]').count(),2);await page.locator('[data-week="all"]').click();await page.locator('#search').fill('Bucky');await page.locator('[data-card="MANIA"]').waitFor({state:'detached'});assert.equal(await page.locator('[data-card]').count(),1);await page.locator('#search').fill('');await page.locator('[data-card="MANIA"]').waitFor();
 await page.locator('#tune').click();assert.equal(await page.locator('[data-setting="historyYears"]').inputValue(),'5');await page.locator('[data-setting="travelWeight"]').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('[data-setting="travelWeight"]').inputValue(),'30');await page.locator('[data-preset="travel"]').click();assert(await page.locator('#show-changes').isVisible());assert((await page.locator('.added').count())>0);await page.locator('#show-changes').click();assert(await page.locator('#changes-only').isChecked());await page.locator('#reset').click();assert.equal(await page.locator('.added').count(),0);await page.locator('#tune').click();
 await page.locator('nav [data-view="team"]').click();assert.equal(await page.locator('#team-picker').inputValue(),'UVA');assert(await page.locator('[data-preference="ECS"]').isDisabled());const assigned=await page.locator('.team-event.chosen select').first().getAttribute('data-preference');await page.locator(`[data-preference="${assigned}"]`).selectOption('avoid');assert.equal(await page.locator(`.team-event.chosen select[data-preference="${assigned}"]`).count(),0);await page.locator('#compare-team').selectOption('GT');assert((await page.locator('.team-compare').textContent()).includes('GT'));
 await page.locator(`[data-explain="${assigned}"]`).click();assert(await page.getByText('Match score before circuit allocation',{exact:true}).isVisible());await page.locator('#close-detail').click();await page.reload();await page.locator('nav [data-view="team"]').click();assert.equal(await page.locator(`[data-preference="${assigned}"]`).inputValue(),'avoid');
 await page.locator('nav [data-view="history"]').click();assert.equal(await page.locator('#history-year').inputValue(),'five');assert.equal(await page.locator('.difficulty-card').count(),17);await page.locator('#history-year').selectOption('2025-2026');assert((await page.locator('#history-body').textContent()).includes('vs 5 years'));await page.locator('[data-field="RCR"]').click();assert(await page.getByText('Five-year baseline',{exact:true}).isVisible());assert((await page.locator('#detail-content').textContent()).includes('Viewing 2025-2026'));await page.screenshot({path:'/private/tmp/atlas-v2-evidence.png'});await page.locator('#close-detail').click();await page.locator('#history-year').selectOption('five');await page.locator('[data-history-mode="breaks"]').click();assert(await page.getByRole('heading',{name:'88% had zero or one weekend off'}).isVisible());assert((await page.locator('#history-body').textContent()).includes('414 gaps'));
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/private/tmp/atlas-v2-breaks-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('nav [data-view="lineups"]').click();await page.locator('#compact-view').click();await page.screenshot({path:'/private/tmp/atlas-v2-mobile.png'});await page.locator('#tune').click();await page.screenshot({path:'/private/tmp/atlas-v2-tune-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#reset').click();await page.locator('#tune').click();await page.locator('nav [data-view="team"]').click();await page.screenshot({path:'/private/tmp/atlas-v2-team-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.setViewportSize({width:320,height:740});for(const v of ['lineups','team','history']){await page.locator(`nav [data-view="${v}"]`).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),v+' overflows 320px');}
 const phone=await browser.newPage({viewport:{width:390,height:844}});await phone.goto('http://127.0.0.1:8110/atlas/');await phone.locator('[data-card]').first().waitFor();assert.equal(await phone.locator('#compact-view').getAttribute('aria-pressed'),'true');await phone.screenshot({path:'/private/tmp/atlas-v2-phone-default.png'});await phone.close();assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);assert.deepEqual(fares,[]);assert.equal((await page.request.get('http://127.0.0.1:8110/atlas/fares.json')).status(),404);assert.equal((await page.request.get('http://127.0.0.1:8110/atlas/server.mjs')).status(),404);
 console.log('PASS: 17 complete lineups, filters, interactive changes, team edits and comparisons, immutable hosts, saved preferences, five-year/single-year history, 414-gap evidence, desktop/390px/320px layouts, no writes or fare requests, private assets excluded.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
