import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';
import {buildAtlas} from '../scripts/build_public.mjs';
const require=createRequire(new URL('../../savetheworld/package.json',import.meta.url)),{chromium}=require('@playwright/test');
await buildAtlas(resolve('raas-planner'),'/private/tmp/raas-public/atlas');
const readFileSnapshot=await readFile('raas-planner/fares.json','utf8');
const server=createServer(async(req,res)=>{try{if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);return res.end();}let path=new URL(req.url,'http://localhost').pathname;const file=resolve('/private/tmp/raas-public','.'+path+(path.endsWith('/')?'index.html':''));if(!file.startsWith('/private/tmp/raas-public/'))throw Error();const body=await readFile(file);res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.json':'application/json'})[extname(file)]||'text/plain');res.end(body);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(8110,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url());});await page.route('**/fares',r=>r.fulfill({contentType:'application/json',body:readFileSnapshot}));
 await page.goto('http://127.0.0.1:8110/atlas/');await page.getByRole('heading',{name:'HooRaas · UVA',exact:true}).waitFor();assert(await page.getByText('All 17 fields have 6–8 teams',{exact:true}).isVisible());
 await page.getByRole('button',{name:'Historical strength',exact:true}).click();await page.locator('#strength-lookback').selectOption('5');await page.getByText('42.50',{exact:true}).waitFor();await page.locator('#strength-competition').selectOption('RCR');assert(await page.getByRole('heading',{name:'Competition field evidence',exact:true}).isVisible());await page.screenshot({path:'/private/tmp/atlas-public-strength.png',fullPage:true});
 await page.getByRole('button',{name:'Published schedule',exact:true}).click();assert.equal(await page.locator('#content input,#content select').count(),0);
 await page.getByRole('button',{name:'Team forecast',exact:true}).click();await page.getByRole('button',{name:'GGG',exact:true}).click();assert.equal(await page.locator('#content input,#content select,#flight-search,#save-fare').count(),0);await page.getByRole('button',{name:'View GGG historical strength',exact:true}).click();assert.equal(await page.locator('#strength-competition').inputValue(),'GGG');
 await page.getByRole('button',{name:'Flight prices',exact:true}).click();assert.equal(await page.locator('#serp-key,#connect-serp,#start-refresh').count(),0);assert(await page.getByRole('heading',{name:'Saved flight prices',exact:true}).isVisible());
 await page.getByRole('button',{name:'Model & sources',exact:true}).click();assert.equal(await page.locator('#import-scenario').count(),0);
 await page.locator('[data-team="target"]').fill('3');await page.locator('[data-team="target"]').blur();await page.reload();assert.equal(await page.locator('[data-team="target"]').inputValue(),'3');assert.equal(await page.locator('#strength-lookback').inputValue(),'5');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/private/tmp/atlas-public-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
 console.log('PASS: public preferences persist; source inputs, API controls and imports are absent; no write requests; historical strength has a separate tab and field selector; desktop/mobile render.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
