// Generated by node taskpup-extension/build.mjs.
(() => {
const defaultPet = {name: 'Biscuit', coat: 'honey', collar: 'sage', roaming: true};
const coats = {
  honey: {fur: '#e6b778', ears: '#b98250', cream: '#fff1d5'},
  cream: {fur: '#f3dfb8', ears: '#c9ad86', cream: '#fff8e8'},
  cocoa: {fur: '#99735e', ears: '#654b40', cream: '#f2dbc0'},
  cloud: {fur: '#d1d5da', ears: '#89939f', cream: '#fff9ef'},
};
const collars = {sage: '#809c76', berry: '#c68193', blue: '#7f9ebb'};
function validatePet(pet = defaultPet) {
  if (!pet || typeof pet.name !== 'string' || !pet.name.trim() || pet.name.trim().length > 24 ||
      !Object.hasOwn(coats, pet.coat) || !Object.hasOwn(collars, pet.collar) || typeof pet.roaming !== 'boolean' || (pet.species !== undefined && !['dog','cat'].includes(pet.species))) {
    throw new Error('Choose a dog name (1–24 characters), coat, and collar.');
  }
  return {name: pet.name.trim(), coat: pet.coat, collar: pet.collar, roaming: pet.roaming,...(pet.species==='cat'?{species:'cat'}:{})};
}

function puppySVG(profile = defaultPet) {
  const {fur, ears, cream} = coats[profile.coat] || coats.honey;
  const collar = collars[profile.collar] || collars.sage;
  if(profile.species==='cat')return `<svg class="puppy" viewBox="0 0 110 110" aria-hidden="true"><ellipse cx="55" cy="98" rx="32" ry="5" fill="#596246" opacity=".12"/><path d="M77 91 Q109 96 96 56" fill="none" stroke="${ears}" stroke-width="10" stroke-linecap="round"/><ellipse cx="55" cy="79" rx="25" ry="22" fill="${fur}"/><ellipse cx="55" cy="85" rx="12" ry="14" fill="${cream}"/><path d="M24 45 L24 10 L46 28 Q56 23 68 28 L89 10 L86 51 Q86 76 55 77 Q22 76 24 45" fill="${fur}" stroke="#645043" stroke-width="1.6"/><path d="M29 32 L29 19 L40 31 M73 31 L84 19 L82 36" fill="#dc9290"/><ellipse cx="39" cy="48" rx="5" ry="6" fill="#3c332f"/><ellipse cx="71" cy="48" rx="5" ry="6" fill="#3c332f"/><path d="M50 58 L60 58 L55 64 Z" fill="#c68193"/><path d="M55 64 Q48 72 44 66 M55 64 Q61 72 66 66 M34 59 L10 55 M34 65 L10 69 M76 59 L101 55 M76 65 L101 69" fill="none" stroke="#645043" stroke-width="1.5"/><path d="M35 76 Q55 84 75 76" fill="none" stroke="${collar}" stroke-width="5"/></svg>`;
  return `<svg class="puppy" viewBox="0 0 110 110" aria-hidden="true">
    <ellipse cx="55" cy="98" rx="31" ry="5" fill="#596246" opacity=".12"/>
    <g class="puppy-tail"><path d="M77 79 Q101 58 95 76 Q91 90 76 88" fill="${ears}" stroke="#645043" stroke-width="1.6"/></g>
    <g class="puppy-body"><path d="M36 67 Q27 80 35 94 Q53 102 77 94 Q83 80 70 67" fill="${fur}" stroke="#645043" stroke-width="1.6"/><ellipse cx="55" cy="83" rx="12" ry="13" fill="${cream}"/>
      <g class="puppy-foot left-foot"><path d="M33 88 Q23 100 35 101 L47 100 L46 88" fill="${fur}" stroke="#645043" stroke-width="1.6" stroke-linejoin="round"/></g><g class="puppy-foot right-foot"><path d="M64 88 L63 100 L77 101 Q86 98 75 87" fill="${fur}" stroke="#645043" stroke-width="1.6" stroke-linejoin="round"/></g></g>
    <g class="puppy-head">
      <path class="puppy-ears" d="M31 26 Q12 14 11 36 Q9 63 24 66 Q34 66 36 46 M77 26 Q95 13 99 37 Q103 61 88 66 Q77 68 75 46" fill="${ears}" stroke="#645043" stroke-width="1.6"/>
      <path d="M29 25 Q53 11 79 26 Q88 40 82 61 Q78 77 55 79 Q30 78 24 61 Q19 42 29 25" fill="${fur}" stroke="#645043" stroke-width="1.6"/>
      <path d="M49 21 Q41 40 49 51 L61 51 Q68 37 61 21" fill="${cream}"/>
      <ellipse cx="54" cy="61" rx="22" ry="15" fill="${cream}"/>
      <g class="puppy-eyes"><g class="puppy-gaze"><ellipse cx="37" cy="48" rx="5.3" ry="6.5" fill="#3c332f"/><ellipse cx="72" cy="48" rx="5.3" ry="6.5" fill="#3c332f"/><circle cx="35.5" cy="45.5" r="1.8" fill="white"/><circle cx="70.5" cy="45.5" r="1.8" fill="white"/></g>
      </g><g class="puppy-smile-eyes" fill="none" stroke="#3c332f" stroke-width="2.6" stroke-linecap="round"><path d="M32 49 Q37 43 42 49 M67 49 Q72 43 77 49"/></g>
      <ellipse cx="29" cy="58" rx="6" ry="3" fill="#dc9290" opacity=".6"/><ellipse cx="80" cy="58" rx="6" ry="3" fill="#dc9290" opacity=".6"/>
      <path d="M48 56 Q54 53 60 56 Q60 62 54 63 Q48 62 48 56" fill="#3c332f"/><path d="M54 63 L54 66 M46 65 Q50 70 54 66 Q59 70 63 65" fill="none" stroke="#3c332f" stroke-width="1.6" stroke-linecap="round"/>
      <path class="puppy-tongue" d="M51 68 Q51 78 56 77 Q61 76 58 68" fill="#df8f96"/>
      <path d="M34 75 Q55 86 76 74" fill="none" stroke="${collar}" stroke-width="5"/><circle cx="55" cy="80" r="3.5" fill="#e6bf66"/>
    </g>
    <g class="puppy-curled"><path d="M24 88 Q18 64 48 62 Q75 52 88 75 Q99 96 69 100 L36 100 Q21 99 24 88" fill="${fur}" stroke="#645043" stroke-width="1.6"/><path d="M82 76 Q101 78 86 91 Q65 105 62 86" fill="${ears}" stroke="#645043" stroke-width="1.6"/><ellipse cx="40" cy="83" rx="20" ry="15" fill="${cream}"/><path d="M24 75 Q12 66 16 87 Q20 97 28 89" fill="${ears}"/><path d="M34 82 Q38 86 42 82" fill="none" stroke="#3c332f" stroke-width="2" stroke-linecap="round"/><ellipse cx="24" cy="87" rx="4" ry="3" fill="#3c332f"/><path d="M39 96 L54 96" stroke="${collar}" stroke-width="4" stroke-linecap="round"/></g>
    <g class="puppy-zzz" fill="#8a9878" font-size="9" font-family="sans-serif"><text x="63" y="52">z</text><text x="74" y="42" font-size="7">z</text></g>
  </svg>`;
}


const COMPANION_CSS=":host{color-scheme:light}*{box-sizing:border-box}button{font:12px/1.5 system-ui,sans-serif;cursor:pointer}.pet{display:block;border:0;background:transparent;padding:0;margin:0;width:100%;height:100%;pointer-events:auto;touch-action:none;opacity:.78;filter:drop-shadow(0 2px 2px #23321b18);border-radius:14px;outline-offset:3px}.pet:hover,.pet:focus-visible{opacity:1}.pet:focus-visible{outline:2px solid #6b8255}.pet svg{display:block;width:100%;height:100%;overflow:visible}.puppy-smile-eyes,.puppy-curled,.puppy-zzz,.puppy-tongue{display:none}.pet[data-rest=true] .puppy-body,.pet[data-rest=true] .puppy-head,.pet[data-rest=true] .puppy-tail{display:none}.pet[data-rest=true] .puppy-curled,.pet[data-rest=true] .puppy-zzz{display:block}.menu{position:absolute;bottom:calc(100% + 10px);right:0;width:min(232px,calc(100vw - 32px));padding:14px;background:#fafaf1;color:#34452e;border:1px solid #d3dcc9;box-shadow:0 8px 28px #17251b24;border-radius:14px;pointer-events:auto;font:12px/1.5 system-ui,sans-serif;text-align:left}.menu[data-corner=left]{left:0;right:auto}.menu[hidden]{display:none}.menu strong{display:block;font-size:15px;overflow-wrap:anywhere}.menu p{margin:7px 0 12px;font-size:12px}.menu button{display:block;width:100%;border:0;border-radius:7px;padding:7px 9px;margin-top:4px;text-align:left;background:#e8efdf;color:#34452e}.menu button:hover,.menu button:focus-visible{background:#d7e4c7;outline:2px solid #6b8255;outline-offset:1px}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}\n";
// Built inside a private IIFE alongside the bundled Task Pup SVG renderer.
if(window.top!==window||globalThis.__taskpupCompanion)return;
globalThis.__taskpupCompanion=true;
// The planner already has the real pet and all its care controls.
if(document.getElementById('pet-wanderer'))return;
let state=null,menuOpen=false,localCorner=null,drag=null,dragged=false,wakeTimer,poseTimer,lastActivity=Date.now(),lastStroll=0,disposed=false;
const host=document.createElement('taskpup-companion');
host.style.cssText='all:initial!important;position:fixed!important;bottom:16px!important;right:16px!important;left:auto!important;width:52px!important;height:58px!important;z-index:2147483646!important;display:none!important;pointer-events:none!important;contain:layout style!important;';
const shadow=host.attachShadow({mode:'closed'});
const sheet=new CSSStyleSheet();sheet.replaceSync(COMPANION_CSS);shadow.adoptedStyleSheets=[sheet];
const petButton=document.createElement('button');petButton.className='pet';petButton.type='button';petButton.setAttribute('aria-label','Task Pup companion');petButton.setAttribute('aria-expanded','false');
const menu=document.createElement('div');menu.className='menu';menu.hidden=true;menu.setAttribute('role','group');menu.setAttribute('aria-label','Companion controls');
const title=document.createElement('strong'),hint=document.createElement('p');menu.append(title,hint);
for(const [label,action] of [['Care in Task Pup','open'],['Move to other corner','move'],['Hide on this website','mute'],['Close','close']]){const button=document.createElement('button');button.type='button';button.textContent=label;button.dataset.action=action;menu.append(button);}
shadow.append(petButton,menu);document.documentElement.append(host);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const editing=()=>{const el=document.activeElement;return !!el&&(el.matches('input,textarea,select,[contenteditable=""],[contenteditable="true"],[role="textbox"]')||el.isContentEditable);};
async function send(message){try{const result=await chrome.runtime.sendMessage(message);if(result?.error)throw new Error(result.error);return result;}catch{dispose();return null;}}
function setMenu(open){menuOpen=open;menu.hidden=!open;petButton.setAttribute('aria-expanded',String(open));if(open)menu.querySelector('button').focus();render();}
function render(){
 if(disposed||!state)return;
 clearTimeout(wakeTimer);
 const {snapshot,settings}=state,now=Date.now();
 const show=!!snapshot?.connected&&settings.enabled&&settings.snoozeUntil<=now&&!settings.mutedHosts.includes(location.hostname)&&!document.hidden&&!document.fullscreenElement;
 host.style.setProperty('display',show?'block':'none','important');
 if(settings.snoozeUntil>now)wakeTimer=setTimeout(render,Math.min(2147483647,settings.snoozeUntil-now+50));
 if(!show){petButton.getAnimations().forEach(animation=>animation.cancel());menuOpen=false;menu.hidden=true;petButton.setAttribute('aria-expanded','false');return;}
 const corner=localCorner||settings.corner;
 host.style.setProperty('width',settings.size+'px','important');host.style.setProperty('height',(settings.size+6)+'px','important');
 host.style.setProperty('left',corner==='left'?'16px':'auto','important');host.style.setProperty('right',corner==='right'?'16px':'auto','important');
 menu.dataset.corner=corner;
 const key=JSON.stringify(snapshot.pet);if(petButton.dataset.profile!==key){petButton.innerHTML=puppySVG(snapshot.pet);petButton.dataset.profile=key;}
 petButton.setAttribute('aria-label',`${snapshot.pet.name}, your Task Pup companion. Open controls.`);
 const focused=!!snapshot.focused&&now-state.updatedAt<120000;
 petButton.dataset.rest=String(focused||editing()||snapshot.care.used===7);
 petButton.dataset.motion=settings.motion==='gentle'&&!reduced.matches&&snapshot.pet.roaming&&!focused&&!editing()&&!menuOpen?'gentle':'still';
 if(petButton.dataset.motion==='still')petButton.getAnimations().forEach(animation=>animation.cancel());
 title.textContent=snapshot.pet.name;
 hint.textContent=focused?'Resting while you focus.':snapshot.care.used===7?'Fed, exercised, and cozy.':now-state.updatedAt>120000?'Showing your last synced companion. Open Task Pup to refresh.':'A little company. Meals and play live in Task Pup.';
}
function receive(next){if(state?.settings.corner!==next.settings.corner)localCorner=null;state=next;render();}
petButton.addEventListener('click',event=>{event.stopPropagation();if(dragged){dragged=false;return;}setMenu(!menuOpen);});
petButton.addEventListener('pointerenter',()=>petButton.getAnimations().forEach(animation=>animation.cancel()));
petButton.addEventListener('pointerdown',event=>{if(event.button!==0)return;petButton.getAnimations().forEach(animation=>animation.cancel());drag={x:event.clientX,y:event.clientY};dragged=false;petButton.setPointerCapture(event.pointerId);});
petButton.addEventListener('pointermove',event=>{if(!drag)return;if(Math.hypot(event.clientX-drag.x,event.clientY-drag.y)>8){dragged=true;host.style.setProperty('left',Math.max(8,Math.min(innerWidth-state.settings.size-8,event.clientX-state.settings.size/2))+'px','important');host.style.setProperty('right','auto','important');}});
function drop(event){if(!drag)return;drag=null;if(dragged){localCorner=event.clientX<innerWidth/2?'left':'right';render();}}
petButton.addEventListener('pointerup',drop);petButton.addEventListener('pointercancel',()=>{drag=null;render();});
menu.addEventListener('click',async event=>{
 const action=event.target.closest('button')?.dataset.action;if(!action)return;
 if(action==='open')await send({type:'OPEN'});
 if(action==='mute')await send({type:'MUTE'});
 if(action==='move')localCorner=(localCorner||state.settings.corner)==='left'?'right':'left';
 setMenu(false);if(action==='close')petButton.focus();
});
function keyboard(event){if(event.key==='Escape'&&menuOpen){setMenu(false);petButton.focus();}}
function outside(event){if(menuOpen&&!event.composedPath().includes(host))setMenu(false);}
function activity(){lastActivity=Date.now();render();}
function onState(message){if(message.type==='STATE')receive(message.state);if(message.type==='REMOVE')dispose();}
function dispose(){
 if(disposed)return;disposed=true;clearTimeout(wakeTimer);clearInterval(poseTimer);host.remove();
 chrome.runtime.onMessage.removeListener(onState);
 document.removeEventListener('visibilitychange',activity);document.removeEventListener('fullscreenchange',activity);document.removeEventListener('focusin',activity);document.removeEventListener('focusout',activity);document.removeEventListener('keydown',keyboard);document.removeEventListener('pointerdown',outside);reduced.removeEventListener('change',render);globalThis.__taskpupCompanion=false;
}
chrome.runtime.onMessage.addListener(onState);
document.addEventListener('visibilitychange',activity);document.addEventListener('fullscreenchange',activity);document.addEventListener('focusin',activity);document.addEventListener('focusout',activity);document.addEventListener('keydown',keyboard);document.addEventListener('pointerdown',outside,{passive:true});reduced.addEventListener('change',render);
// No animation-frame loop, whole-page observer, scrolling handler, or page scan.
// A short edge stroll is opt-in and only happens after two quiet minutes.
poseTimer=setInterval(()=>{render();if(!document.hidden&&!menuOpen&&!editing()&&Date.now()-lastActivity>120000&&Date.now()-lastStroll>120000&&petButton.dataset.motion==='gentle'){lastStroll=Date.now();const distance=(localCorner||state.settings.corner)==='right'?-24:24;petButton.animate([{transform:'translateX(0)'},{transform:`translateX(${distance}px)`,offset:.5},{transform:'translateX(0)'}],{duration:6000,easing:'ease-in-out'});}},60000);
send({type:'GET'}).then(initial=>{if(initial?.allowed)receive(initial);});

})();
